import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { baixarCsv, fiscalProduto, gerarCsv, gtinValido, imagem, lerCsv, moeda, normalizar, numero, pendencias, publicado, situacaoProduto, type ProdutoCatalogo } from './catalogoUtils';
import './gestao-produtos.css';
type Props = { backendUrl: string; token: string; lojaId: string; nomeLoja: string; onClose: () => void; onEstoque?: () => void; onVitrine?: () => void; onDirtyChange?: (value: boolean) => void; refreshKey?: number };
type Saldo = { id: string; saldo: number | null };
type Movimento = { produtoId: string; tipo: string; quantidade: number; referencia?: string; criadoEm: string };
type Historico = { id: number; acao: string; autor: string; criadoEm: string; dados: ProdutoCatalogo };
type Aba = 'geral' | 'precos' | 'imagens' | 'estoque' | 'fiscal' | 'publicacao' | 'historico';
const ABAS: { key: Aba; titulo: string }[] = [{ key: 'geral', titulo: 'Informações gerais' }, { key: 'precos', titulo: 'Preços e custos' }, { key: 'imagens', titulo: 'Imagens' }, { key: 'estoque', titulo: 'Estoque e envio' }, { key: 'fiscal', titulo: 'Dados fiscais' }, { key: 'publicacao', titulo: 'Publicação e busca' }, { key: 'historico', titulo: 'Histórico' }];
const VAZIO = { nome: '', codigoInterno: '', codigoBarras: '', preco: '', precoPromocional: '', custo: '', marca: '', fabricante: '', descricao: '', categoria: '', subcategoria: '', ncm: '', cest: '', cfop: '', icmsSituacao: '', unidade: '', estoqueMinimo: '', peso: '', altura: '', largura: '', comprimento: '', seoTitulo: '', seoDescricao: '' };
type Campos = typeof VAZIO;
const NUMERICOS: (keyof Campos)[] = ['preco', 'precoPromocional', 'custo', 'estoqueMinimo', 'peso', 'altura', 'largura', 'comprimento'];
const ABA_CAMPO: Partial<Record<keyof Campos, Aba>> = { preco: 'precos', custo: 'precos', precoPromocional: 'precos', ncm: 'fiscal', cest: 'fiscal', cfop: 'fiscal', icmsSituacao: 'fiscal', unidade: 'fiscal', estoqueMinimo: 'estoque', peso: 'estoque', altura: 'estoque', largura: 'estoque', comprimento: 'estoque', seoTitulo: 'publicacao', seoDescricao: 'publicacao' };
const rotulos = { rascunho: 'Rascunho', ativo: 'Ativo', arquivado: 'Arquivado' };
function Icone({ nome, size = 20 }: { nome: 'box' | 'search' | 'plus' | 'arrow' | 'upload' | 'check' | 'image'; size?: number }) { const paths = { box: 'M21 8 12 3 3 8v8l9 5 9-5z M3 8l9 5 9-5 M12 13v8', search: 'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', plus: 'M12 5v14 M5 12h14', arrow: 'M19 12H5 M12 5l-7 7 7 7', upload: 'M12 16V3 M7 8l5-5 5 5 M3 16v5h18v-5', check: 'M5 12l4 4L19 6', image: 'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5 M15 7h.01' }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[nome]} /></svg>; }
function Campo({ nome, titulo, children, ajuda, erro, largo }: { nome: string; titulo: string; children: ReactNode; ajuda?: string; erro?: string; largo?: boolean }) { return <div className={`pc-field ${largo ? 'pc-field-wide' : ''}`}><label htmlFor={`pc-${nome}`}>{titulo}</label>{children}{erro ? <span className="pc-field-error" id={`pc-${nome}-hint`}>{erro}</span> : ajuda && <small id={`pc-${nome}-hint`}>{ajuda}</small>}</div>; }
function Foto({ url, backend, nome }: { url?: string; backend: string; nome: string }) { return url ? <img src={imagem(url, backend)} alt={nome} loading="lazy" /> : <span className="pc-photo-empty"><Icone nome="image" /></span>; }
export default function GestaoProdutos({ backendUrl, token, lojaId, nomeLoja, onClose, onEstoque, onVitrine, onDirtyChange, refreshKey }: Props) {
 const [produtos, setProdutos] = useState<ProdutoCatalogo[]>([]), [saldos, setSaldos] = useState<Saldo[]>([]), [movimentos, setMovimentos] = useState<Movimento[]>([]);
 const [carregando, setCarregando] = useState(true), [estoqueErro, setEstoqueErro] = useState(false), [erro, setErro] = useState(''), [aviso, setAviso] = useState('');
 const [busca, setBusca] = useState(''), [filtro, setFiltro] = useState('todos'), [categoria, setCategoria] = useState(''), [qualidade, setQualidade] = useState(''), [ordem, setOrdem] = useState('nome'), [pagina, setPagina] = useState(1), [tamanho, setTamanho] = useState(20);
 const [selecionados, setSelecionados] = useState<string[]>([]), [acaoLote, setAcaoLote] = useState(''), [valorLote, setValorLote] = useState(''), [ocupado, setOcupado] = useState(false);
 const [editando, setEditando] = useState<ProdutoCatalogo | 'novo' | null>(null), [campos, setCampos] = useState<Campos>(VAZIO), [galeria, setGaleria] = useState<string[]>([]), [situacao, setSituacao] = useState<NonNullable<ProdutoCatalogo['situacao']>>('rascunho'), [visivel, setVisivel] = useState(false), [aba, setAba] = useState<Aba>('geral'), [erros, setErros] = useState<Record<string, string>>({});
 const [historico, setHistorico] = useState<Historico[]>([]), [historicoErro, setHistoricoErro] = useState(''), [historicoCarregando, setHistoricoCarregando] = useState(false);
 const [upload, setUpload] = useState(false), [importacao, setImportacao] = useState(false), [linhas, setLinhas] = useState<Record<string, unknown>[]>([]), [previa, setPrevia] = useState<{ resumo: { novos: number; atualizados: number; total: number }; produtos: ProdutoCatalogo[] } | null>(null);
 const fotoInput = useRef<HTMLInputElement>(null), arquivoInput = useRef<HTMLInputElement>(null), baseline = useRef('');
 const id = editando && editando !== 'novo' ? editando.id : null;
 const dirty = !!editando && baseline.current !== JSON.stringify({ campos, galeria, situacao, visivel });
 useEffect(() => { onDirtyChange?.(dirty); }, [dirty, onDirtyChange]);
 useEffect(() => () => onDirtyChange?.(false), [onDirtyChange]);
 const categorias = [...new Set(produtos.map(p => p.categoria).filter((c): c is string => !!c))].sort();
 const saldoMap = useMemo(() => new Map(saldos.map(s => [s.id, s.saldo])), [saldos]);
 async function api<T>(path: string, options: RequestInit = {}): Promise<T> { const r = await fetch(backendUrl + '/api/gestao' + path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers } }); const body = await r.json().catch(() => ({})); if (!r.ok) { const e = new Error(body.error || 'Não foi possível concluir a operação.') as Error & { campos?: Record<string, string> }; e.campos = body.campos; throw e; } return body as T; }
 async function carregar() { setCarregando(true); setErro(''); setEstoqueErro(false); const [catalogo, estoque] = await Promise.allSettled([api<ProdutoCatalogo[]>('/produtos'), api<{ produtos: Saldo[]; movimentos: Movimento[] }>('/estoque')]); if (catalogo.status === 'fulfilled') setProdutos(catalogo.value); else setErro(catalogo.reason?.message || 'Erro ao carregar produtos.'); if (estoque.status === 'fulfilled') { setSaldos(estoque.value.produtos); setMovimentos(estoque.value.movimentos); } else setEstoqueErro(true); setCarregando(false); }
 useEffect(() => { void carregar(); }, [lojaId, token, backendUrl, refreshKey]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(() => { setPagina(1); }, [busca, filtro, categoria, qualidade, ordem, tamanho]);
 useEffect(() => { const fn = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', fn); return () => window.removeEventListener('beforeunload', fn); }, [dirty]);
 useEffect(() => { if (aba !== 'historico' || !id) return; let ativo = true; setHistoricoCarregando(true); setHistoricoErro(''); api<Historico[]>(`/produtos/${encodeURIComponent(id)}/historico`).then(h => { if (ativo) setHistorico(h); }).catch(e => { if (ativo) setHistoricoErro(e.message); }).finally(() => { if (ativo) setHistoricoCarregando(false); }); return () => { ativo = false; }; }, [id, aba]); // eslint-disable-line react-hooks/exhaustive-deps
 function abrir(p: ProdutoCatalogo | 'novo') { const f = { ...VAZIO }; if (p !== 'novo') for (const k of Object.keys(f) as (keyof Campos)[]) { const v = p[k]; f[k] = v === undefined ? '' : typeof v === 'number' ? String(v).replace('.', ',') : String(v); } if (p !== 'novo' && f.codigoInterno === p.id) f.codigoInterno = ''; const g = p === 'novo' ? [] : p.imagens?.length ? p.imagens : p.imagemUrl ? [p.imagemUrl] : []; const st = p === 'novo' ? 'rascunho' : situacaoProduto(p), vi = p === 'novo' ? false : publicado(p); baseline.current = JSON.stringify({ campos: f, galeria: g, situacao: st, visivel: vi }); setCampos(f); setGaleria(g); setSituacao(st); setVisivel(vi); setEditando(p); setAba('geral'); setErros({}); setErro(''); setAviso(''); window.scrollTo({ top: 0 }); }
 function voltar() { if (ocupado || upload) return; if (dirty && !window.confirm('Descartar as alterações não salvas deste produto?')) return; setEditando(null); setErro(''); setErros({}); }
 const filtrados = useMemo(() => produtos.filter(p => [p.nome, p.codigoInterno || '', p.codigoBarras || '', p.marca || ''].some(v => normalizar(v).includes(normalizar(busca.trim()))) && (filtro === 'todos' || (filtro === 'publicados' ? publicado(p) : situacaoProduto(p) === filtro)) && (!categoria || p.categoria === categoria) && (!qualidade || (qualidade === 'pendencias' ? pendencias(p).length > 0 : qualidade === 'fiscal' ? fiscalProduto(p) !== 'Específico' : qualidade === 'semestoque' ? saldoMap.get(p.id) === 0 : !publicado(p)))).sort((a, b) => ordem === 'preco' ? (a.precoPromocional || a.preco) - (b.precoPromocional || b.preco) : ordem === 'preco-desc' ? (b.precoPromocional || b.preco) - (a.precoPromocional || a.preco) : ordem === 'codigo' ? (a.codigoInterno || '').localeCompare(b.codigoInterno || '') : a.nome.localeCompare(b.nome, 'pt-BR')), [produtos, busca, filtro, categoria, qualidade, ordem, saldoMap]);
 const paginas = Math.max(1, Math.ceil(filtrados.length / tamanho)), atual = Math.min(pagina, paginas), visiveis = filtrados.slice((atual - 1) * tamanho, atual * tamanho);
 function atualizarLista(itens: ProdutoCatalogo[]) { setProdutos(v => { const porId = new Map(v.map(p => [p.id, p])); for (const p of itens) porId.set(p.id, p); return [...porId.values()]; }); }
 const input = (k: keyof Campos, titulo: string, opts: { ajuda?: string; largo?: boolean; limite?: number; placeholder?: string; numeric?: boolean; area?: boolean } = {}) => { const props = { id: `pc-${k}`, value: campos[k], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => { setCampos(f => ({ ...f, [k]: e.target.value })); setErros(v => ({ ...v, [k]: '' })); }, disabled: ocupado, maxLength: opts.limite || 255, placeholder: opts.placeholder, 'aria-invalid': !!erros[k], 'aria-describedby': opts.ajuda || erros[k] ? `pc-${k}-hint` : undefined }; return <Campo nome={k} titulo={titulo} ajuda={opts.ajuda} erro={erros[k]} largo={opts.largo}>{opts.area ? <textarea {...props} rows={5} /> : <input {...props} inputMode={opts.numeric ? 'decimal' : 'text'} list={k === 'categoria' ? 'pc-categorias' : undefined} />}</Campo>; };
 async function salvar(e: React.FormEvent) { e.preventDefault(); setErro(''); setErros({}); const problemas: Record<string, string> = {}; if (!campos.nome.trim()) problemas.nome = 'Informe o nome do produto.'; if (!campos.preco.trim() || !Number.isFinite(numero(campos.preco)) || numero(campos.preco) <= 0) problemas.preco = 'Informe um preço maior que zero.'; const eanMudou = editando === 'novo' || editando && editando.codigoBarras !== campos.codigoBarras.trim(); if (campos.codigoBarras.trim() && eanMudou && !gtinValido(campos.codigoBarras.trim())) problemas.codigoBarras = 'EAN inválido. Confira os dígitos da embalagem.'; if (situacao === 'ativo' && !campos.codigoBarras.trim()) problemas.codigoBarras = 'Informe o EAN para ativar o produto.'; if (Object.keys(problemas).length) { setErros(problemas); setAba(ABA_CAMPO[Object.keys(problemas)[0] as keyof Campos] || 'geral'); setErro('Revise os campos destacados.'); return; } setOcupado(true); try { const body: Record<string, unknown> = { ...campos, imagens: galeria, imagemUrl: galeria[0] || '', situacao, publicado: visivel && situacao === 'ativo' }; for (const k of NUMERICOS) body[k] = campos[k].trim() ? numero(campos[k]) : null; const p = await api<ProdutoCatalogo>(id ? `/produtos/${encodeURIComponent(id)}` : '/produtos', { method: id ? 'PUT' : 'POST', body: JSON.stringify(body) }); atualizarLista([p]); setEditando(null); setAviso(id ? 'Alterações salvas.' : 'Produto cadastrado.'); setSelecionados([]); } catch (e) { const err = e as Error & { campos?: Record<string, string> }; setErro(err.message); setErros(err.campos || {}); const k = Object.keys(err.campos || {})[0]; setAba(k === 'imagens' ? 'imagens' : k === 'publicado' || k === 'situacao' ? 'publicacao' : ABA_CAMPO[k as keyof Campos] || 'geral'); } finally { setOcupado(false); } }
 async function enviarFotos(files: FileList | null) { if (!files) return; const lista = [...files]; if (galeria.length + lista.length > 8) { setErro('Use até 8 imagens por produto.'); return; } if (lista.some(f => !/^image\/(png|jpeg|webp)$/.test(f.type) || f.size > 3 * 1024 * 1024)) { setErro('Envie PNG, JPG ou WEBP com até 3 MB por imagem.'); return; } setUpload(true); setErro(''); try { for (const f of lista) { const dataUrl = await new Promise<string>((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result)); r.onerror = reject; r.readAsDataURL(f); }); const r = await api<{ url: string }>('/upload', { method: 'POST', body: JSON.stringify({ dataUrl }) }); setGaleria(g => [...g, r.url]); } } catch (e) { setErro(e instanceof Error ? e.message : 'Falha ao enviar a imagem.'); } finally { setUpload(false); if (fotoInput.current) fotoInput.current.value = ''; } }
 async function lote() { if (!acaoLote || !selecionados.length) return; setOcupado(true); setErro(''); const alteracoes = acaoLote === 'publicar' ? { publicado: true } : acaoLote === 'ocultar' ? { publicado: false } : acaoLote === 'categoria' ? { categoria: valorLote } : acaoLote === 'promocao' ? { precoPromocional: numero(valorLote) } : acaoLote === 'limpar-promocao' ? { precoPromocional: null } : { situacao: acaoLote }; try { const salvos = await api<ProdutoCatalogo[]>('/produtos/lote', { method: 'PUT', body: JSON.stringify({ ids: selecionados, alteracoes }) }); atualizarLista(salvos); setAviso(`${salvos.length} produtos atualizados.`); setSelecionados([]); setAcaoLote(''); setValorLote(''); } catch (e) { setErro(e instanceof Error ? e.message : 'Falha na alteração em lote.'); } finally { setOcupado(false); } }
 async function importar(file?: File) { if (!file) return; setOcupado(true); setErro(''); setPrevia(null); setLinhas([]); try { if (file.size > 2 * 1024 * 1024) throw new Error('Use um arquivo CSV de até 2 MB.'); const l = lerCsv(await file.text()); setLinhas(l); setPrevia(await api('/produtos/importar', { method: 'POST', body: JSON.stringify({ linhas: l }) })); } catch (e) { setErro(e instanceof Error ? e.message : 'Falha ao importar.'); } finally { setOcupado(false); if (arquivoInput.current) arquivoInput.current.value = ''; } }
 async function confirmarImportacao() { setOcupado(true); setErro(''); try { const r = await api<NonNullable<typeof previa>>('/produtos/importar', { method: 'POST', body: JSON.stringify({ linhas, confirmar: true }) }); atualizarLista(r.produtos); setAviso(`${r.resumo.total} produtos importados.`); setImportacao(false); setPrevia(null); setLinhas([]); } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao importar.'); } finally { setOcupado(false); } }
 const notices = <>{erro && <div className="pc-notice pc-notice-error" role="alert">{erro}</div>}{aviso && <div className="pc-notice pc-notice-success" role="status"><Icone nome="check" />{aviso}<button type="button" onClick={() => setAviso('')} aria-label="Fechar aviso">×</button></div>}</>;
 useEffect(() => {
   if (!importacao) return;
   const anterior = document.activeElement as HTMLElement | null;
   const dialog = document.getElementById('pc-import-dialog');
   dialog?.querySelector<HTMLButtonElement>('button')?.focus();
   const overflowAnterior = document.body.style.overflow;
   document.body.style.overflow = 'hidden';
   return () => { document.body.style.overflow = overflowAnterior; anterior?.focus(); };
 }, [importacao]);
 function tecladoImportacao(e: React.KeyboardEvent<HTMLElement>) {
   if (e.key === 'Escape' && !ocupado) { setImportacao(false); setPrevia(null); setErro(''); }
   if (e.key !== 'Tab') return;
   const elementos = [...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not([hidden]):not(:disabled), select:not(:disabled)')];
   const primeiro = elementos[0], ultimo = elementos.at(-1);
   if (e.shiftKey && document.activeElement === primeiro) { e.preventDefault(); ultimo?.focus(); }
   else if (!e.shiftKey && document.activeElement === ultimo) { e.preventDefault(); primeiro?.focus(); }
 }
 const saldo = id ? saldoMap.get(id) : undefined;
 return <div className="pc-workspace">
 {!editando ? <>
 <header className="pc-heading"><div><span className="pc-eyebrow">CATÁLOGO · {nomeLoja}</span><h2>Produtos <span className="pc-count">{produtos.length}</span></h2><p>Organize seu catálogo e prepare seus produtos para vender.</p></div><div className="pc-actions"><button type="button" className="pc-btn" onClick={() => { setImportacao(true); setErro(''); }} disabled={ocupado}>Importar</button><button type="button" className="pc-btn" onClick={() => baixarCsv('produtos.csv', gerarCsv(selecionados.length ? produtos.filter(p => selecionados.includes(p.id)) : filtrados))} disabled={carregando || !filtrados.length}>Exportar</button><button type="button" className="pc-btn pc-btn-primary" onClick={() => abrir('novo')}><Icone nome="plus" size={17} />Novo produto</button></div></header>
 {notices}
 <div className="pc-metrics">{[{ label: 'Publicados na vitrine', valor: produtos.filter(publicado).length, filtro: 'publicados', tom: 'green' }, { label: 'Em rascunho', valor: produtos.filter(p => situacaoProduto(p) === 'rascunho').length, filtro: 'rascunho', tom: 'blue' }, { label: 'Com pendências', valor: produtos.filter(p => pendencias(p).length).length, filtro: 'pendencias', tom: 'amber' }, { label: 'Produtos sem saldo', valor: estoqueErro ? '—' : saldos.filter(p => p.saldo === 0).length, filtro: 'semestoque', tom: 'rose' }].map(m => <button key={m.label} type="button" className={`pc-metric pc-metric-${m.tom}`} onClick={() => { if (['pendencias', 'semestoque'].includes(m.filtro)) { setQualidade(m.filtro); setFiltro('todos'); } else { setFiltro(m.filtro); setQualidade(''); } }}><span>{m.label}</span><strong>{m.valor}</strong><small>Ver produtos →</small></button>)}</div>
 <section className="pc-catalog" aria-label="Lista de produtos"><div className="pc-tabs">{['todos', 'ativo', 'rascunho', 'arquivado'].map(v => <button key={v} type="button" aria-pressed={filtro === v} onClick={() => setFiltro(v)}>{v === 'todos' ? 'Todos' : rotulos[v as keyof typeof rotulos]} <span>{v === 'todos' ? produtos.length : produtos.filter(p => situacaoProduto(p) === v).length}</span></button>)}</div>
 <div className="pc-toolbar"><label className="pc-search"><Icone nome="search" size={18} /><input type="search" aria-label="Pesquisar produtos" value={busca} onChange={e => setBusca(e.target.value)} placeholder="Nome, código interno, EAN ou marca" /></label><select aria-label="Filtrar por categoria" value={categoria} onChange={e => setCategoria(e.target.value)}><option value="">Todas as categorias</option>{categorias.map(c => <option key={c}>{c}</option>)}</select><select aria-label="Filtrar por pendência" value={qualidade} onChange={e => setQualidade(e.target.value)}><option value="">Todos os cadastros</option><option value="pendencias">Com pendências</option><option value="fiscal">Fiscal usa padrão da loja</option><option value="semestoque">Sem saldo</option><option value="ocultos">Ocultos da vitrine</option></select><select aria-label="Ordenar produtos" value={ordem} onChange={e => setOrdem(e.target.value)}><option value="nome">Nome: A–Z</option><option value="codigo">Código interno</option><option value="preco">Menor preço</option><option value="preco-desc">Maior preço</option></select><button className="pc-btn pc-btn-icon" type="button" aria-label="Atualizar catálogo" disabled={carregando || ocupado} onClick={() => void carregar()}>↻</button></div>
 {(busca || categoria || qualidade || filtro !== 'todos') && <div className="pc-filter-summary">{filtrados.length} produtos encontrados<button type="button" onClick={() => { setBusca(''); setCategoria(''); setQualidade(''); setFiltro('todos'); }}>Limpar filtros</button></div>}
 {selecionados.length > 0 && <div className="pc-bulk"><strong>{selecionados.length} selecionados</strong><select aria-label="Ação em lote" value={acaoLote} disabled={ocupado} onChange={e => setAcaoLote(e.target.value)}><option value="">Escolha uma ação</option><option value="publicar">Publicar na vitrine</option><option value="ocultar">Ocultar da vitrine</option><option value="ativo">Ativar cadastros</option><option value="rascunho">Mover para rascunho</option><option value="arquivado">Arquivar cadastros</option><option value="categoria">Alterar categoria</option><option value="promocao">Definir preço promocional</option><option value="limpar-promocao">Remover promoções</option></select>{['categoria', 'promocao'].includes(acaoLote) && <input aria-label="Valor da alteração em lote" placeholder={acaoLote === 'categoria' ? 'Nova categoria' : 'Preço promocional (R$)'} value={valorLote} disabled={ocupado} onChange={e => setValorLote(e.target.value)} />}<button className="pc-btn pc-btn-primary" type="button" disabled={ocupado || !acaoLote || ['categoria', 'promocao'].includes(acaoLote) && !valorLote.trim() || selecionados.length > 100} onClick={() => void lote()}>{ocupado ? 'Aplicando…' : 'Aplicar'}</button><button className="pc-btn" type="button" disabled={ocupado} onClick={() => setSelecionados([])}>Limpar seleção</button>{selecionados.length > 100 && <small>Limite de 100 por operação.</small>}</div>}
 {estoqueErro && <div className="pc-notice">Não foi possível consultar o estoque. Os saldos estão indisponíveis.</div>}
 <div className="pc-table-wrap"><table><caption className="pc-sr-only">Catálogo de produtos da loja</caption><thead><tr><th className="pc-check"><input type="checkbox" aria-label="Selecionar produtos desta página" checked={visiveis.length > 0 && visiveis.every(p => selecionados.includes(p.id))} disabled={ocupado || !visiveis.length} onChange={e => setSelecionados(v => e.target.checked ? [...new Set([...v, ...visiveis.map(p => p.id)])] : v.filter(id => !visiveis.some(p => p.id === id)))} /></th><th>Produto</th><th>Preço</th><th>Estoque</th><th>Cadastro</th><th>Vitrine</th><th>Fiscal</th><th><span className="pc-sr-only">Ações</span></th></tr></thead><tbody>{visiveis.map(p => <tr key={p.id} className={selecionados.includes(p.id) ? 'pc-selected' : ''}><td className="pc-check"><input type="checkbox" aria-label={`Selecionar ${p.nome}`} checked={selecionados.includes(p.id)} disabled={ocupado} onChange={() => setSelecionados(v => v.includes(p.id) ? v.filter(x => x !== p.id) : [...v, p.id])} /></td><td><button type="button" className="pc-product-link" onClick={() => abrir(p)}><span className="pc-thumb"><Foto backend={backendUrl} url={p.imagemUrl} nome={p.nome} /></span><span><strong>{p.nome}</strong><small>{p.codigoInterno && p.codigoInterno !== p.id ? p.codigoInterno : 'Código interno não definido'}{p.marca ? ` · ${p.marca}` : ''}</small><small>{p.categoria || 'Sem categoria'}</small></span></button>{pendencias(p).length > 0 && <span className="pc-pending">Completar: {pendencias(p).join(', ')}</span>}</td><td><strong>{moeda(p.precoPromocional || p.preco)}</strong>{p.precoPromocional && <del>{moeda(p.preco)}</del>}</td><td><strong>{estoqueErro ? '—' : saldoMap.get(p.id) ?? '—'}</strong><small>{estoqueErro ? 'Indisponível' : saldoMap.get(p.id) == null ? 'Sem controle' : saldoMap.get(p.id) === 0 ? 'Esgotado' : p.estoqueMinimo !== undefined && (saldoMap.get(p.id) || 0) <= p.estoqueMinimo ? 'Estoque baixo' : 'Disponível'}</small></td><td><span className={`pc-badge pc-badge-${situacaoProduto(p)}`}>{rotulos[situacaoProduto(p)]}</span></td><td><span className={`pc-dot ${publicado(p) ? 'pc-dot-green' : ''}`}>{publicado(p) ? 'Publicado' : 'Oculto'}</span></td><td><span className="pc-fiscal">{fiscalProduto(p)}</span></td><td><button type="button" className="pc-btn pc-btn-small" onClick={() => abrir(p)} aria-label={`Editar ${p.nome}`}>Editar</button></td></tr>)}</tbody></table></div>
 {carregando && <div className="pc-empty" role="status">Carregando catálogo…</div>}{!carregando && !visiveis.length && <div className="pc-empty"><Icone nome="box" size={40} /><h3>{produtos.length ? 'Nenhum produto encontrado' : 'Seu catálogo começa aqui'}</h3><p>{produtos.length ? 'Ajuste a busca ou os filtros.' : 'Cadastre seu primeiro produto ou importe uma planilha.'}</p><button type="button" className="pc-btn pc-btn-primary" onClick={() => abrir('novo')}>Cadastrar produto</button></div>}
 <footer className="pc-pagination"><span>{filtrados.length ? `${(atual - 1) * tamanho + 1}–${Math.min(atual * tamanho, filtrados.length)}` : '0'} de {filtrados.length} produtos</span><label>Por página<select aria-label="Produtos por página" value={tamanho} onChange={e => setTamanho(Number(e.target.value))}>{[20, 50, 100].map(n => <option key={n}>{n}</option>)}</select></label><button type="button" className="pc-btn pc-btn-small" disabled={atual <= 1} onClick={() => setPagina(atual - 1)}>Anterior</button><span>{atual} / {paginas}</span><button type="button" className="pc-btn pc-btn-small" disabled={atual >= paginas} onClick={() => setPagina(atual + 1)}>Próxima</button></footer>
 </section><div className="pc-bottom-links"><span>Cadastro, estoque e publicação têm controles independentes.</span><button type="button" onClick={onVitrine}>Configurar vitrine →</button><button type="button" onClick={onClose}>Voltar aos pedidos</button></div>
 </> : <form onSubmit={salvar} noValidate>
 <header className="pc-heading pc-editor-heading"><div><button type="button" className="pc-back" disabled={ocupado || upload} onClick={voltar}><Icone nome="arrow" size={17} />Produtos</button><h2>{id ? campos.nome || 'Editar produto' : 'Novo produto'}</h2><p>{id ? 'Atualize as informações e salve suas alterações.' : 'Comece pelo cadastro e publique quando estiver pronto.'}</p></div><span className={`pc-badge pc-badge-${situacao}`}>{rotulos[situacao]}</span></header>
 {notices}<div className="pc-editor-layout"><nav className="pc-editor-nav" aria-label="Seções do produto">{ABAS.map((a, i) => <button key={a.key} type="button" disabled={a.key === 'historico' && !id} className={aba === a.key ? 'is-active' : ''} aria-current={aba === a.key ? 'step' : undefined} onClick={() => setAba(a.key)}><span>{String(i + 1).padStart(2, '0')}</span>{a.titulo}{a.key === 'imagens' && <small>{galeria.length}</small>}</button>)}</nav>
 <section className="pc-editor-card" aria-label={ABAS.find(a => a.key === aba)?.titulo}><div className="pc-section-title"><h3>{ABAS.find(a => a.key === aba)?.titulo}</h3><p>{aba === 'geral' ? 'Identifique o produto e organize seu catálogo.' : aba === 'fiscal' ? 'Campos vazios usam os padrões fiscais da loja.' : aba === 'imagens' ? 'A primeira imagem é a principal e aparece na vitrine.' : aba === 'historico' ? 'Últimas 50 alterações salvas neste produto.' : aba === 'publicacao' ? 'Controle quando o produto aparece para seus clientes.' : aba === 'estoque' ? 'O saldo disponível já considera as baixas dos pedidos recebidos.' : 'Defina o preço de venda e acompanhe a margem estimada.'}</p></div>
 {aba === 'geral' && <div className="pc-field-grid">{input('nome', 'Nome do produto *', { largo: true, placeholder: 'Ex.: Dipirona 500 mg, caixa com 20 comprimidos' })}{input('codigoInterno', 'Código interno / SKU', { limite: 60, ajuda: 'Único para sua loja. Vazio gera um SKU automaticamente.', placeholder: 'Ex.: MED-001' })}{input('codigoBarras', 'EAN / GTIN', { limite: 14, ajuda: 'Leia o código da embalagem. Necessário para ativar e conferir na separação.', placeholder: '8, 12, 13 ou 14 dígitos', numeric: true })}{input('marca', 'Marca', { limite: 120 })}{input('fabricante', 'Fabricante', { limite: 120 })}{input('categoria', 'Categoria', { limite: 120 })}{input('subcategoria', 'Subcategoria', { limite: 120 })}<datalist id="pc-categorias">{categorias.map(c => <option key={c} value={c} />)}</datalist>{input('descricao', 'Descrição do produto', { largo: true, area: true, limite: 5000, ajuda: `${campos.descricao.length} / 5.000 caracteres`, placeholder: 'Apresentação, características e informações úteis para o cliente.' })}</div>}
 {aba === 'precos' && <><div className="pc-field-grid">{input('preco', 'Preço de venda (R$) *', { numeric: true, placeholder: '0,00' })}{input('custo', 'Custo de aquisição (R$)', { numeric: true, placeholder: '0,00' })}{input('precoPromocional', 'Preço promocional (R$)', { numeric: true, ajuda: 'Opcional. Deve ser menor que o preço normal.', placeholder: '0,00' })}</div><div className="pc-price-summary"><div><small>Preço praticado</small><strong>{moeda(numero(campos.precoPromocional || campos.preco) || 0)}</strong></div><div><small>Margem estimada</small><strong>{campos.custo && numero(campos.precoPromocional || campos.preco) > 0 ? (((numero(campos.precoPromocional || campos.preco) - numero(campos.custo)) / numero(campos.precoPromocional || campos.preco)) * 100).toFixed(1).replace('.', ',') + '%' : '—'}</strong></div></div><p className="pc-help">A margem compara preço e custo informado. Não inclui impostos, taxas ou entrega.</p></>}
 {aba === 'imagens' && <><button type="button" className="pc-dropzone" disabled={upload || ocupado || galeria.length >= 8} onClick={() => fotoInput.current?.click()}><Icone nome="upload" size={32} /><strong>{upload ? 'Enviando imagens…' : 'Selecionar imagens'}</strong><span>PNG, JPG ou WEBP · até 3 MB por imagem · máximo de 8</span></button><input ref={fotoInput} type="file" accept="image/png,image/jpeg,image/webp" multiple hidden onChange={e => void enviarFotos(e.target.files)} /><div className="pc-gallery">{galeria.map((url, i) => <article key={url}><Foto url={url} backend={backendUrl} nome={`${campos.nome || 'Produto'} — foto ${i + 1}`} /><span className="pc-badge">{i === 0 ? 'Principal' : `Imagem ${i + 1}`}</span><div>{i > 0 && <button type="button" disabled={upload || ocupado} onClick={() => setGaleria(g => [url, ...g.filter(u => u !== url)])}>Tornar principal</button>}{i > 1 && <button type="button" disabled={upload || ocupado} aria-label={`Mover imagem ${i + 1} para a esquerda`} onClick={() => setGaleria(g => { const v = [...g]; [v[i - 1], v[i]] = [v[i], v[i - 1]]; return v; })}>←</button>}<button type="button" disabled={upload || ocupado} onClick={() => setGaleria(g => g.filter(u => u !== url))}>Remover</button></div></article>)}</div>{erros.imagens && <p role="alert" className="pc-field-error">{erros.imagens}</p>}</>}
 {aba === 'estoque' && <><div className="pc-price-summary"><div><small>Saldo disponível</small><strong>{estoqueErro ? '—' : saldo ?? '—'}</strong><span>{!id ? 'Salve o produto para receber mercadorias.' : saldo == null ? 'Controle não iniciado' : saldo === 0 ? 'Esgotado' : 'Unidades disponíveis'}</span></div><button type="button" className="pc-btn" onClick={onEstoque} disabled={!id || dirty}>Receber mercadorias →</button></div>{dirty && <p className="pc-help">Salve as alterações antes de abrir o estoque.</p>}<div className="pc-field-grid">{input('estoqueMinimo', 'Estoque mínimo', { numeric: true, ajuda: 'Alerta quando o saldo atingir este valor.' })}{input('peso', 'Peso (kg)', { numeric: true })}{input('altura', 'Altura (cm)', { numeric: true })}{input('largura', 'Largura (cm)', { numeric: true })}{input('comprimento', 'Comprimento (cm)', { numeric: true })}</div>{id && <><h4>Movimentações recentes</h4>{movimentos.filter(m => m.produtoId === id).slice(0, 8).map((m, i) => <div className="pc-history-item" key={i}><strong>{m.tipo === 'ENTRADA' ? 'Recebimento' : m.tipo === 'VENDA' ? 'Venda' : 'Estorno'} · {m.quantidade} unidades</strong><span>{new Date(m.criadoEm).toLocaleString('pt-BR')} {m.referencia && `· ${m.referencia}`}</span></div>)}{!movimentos.some(m => m.produtoId === id) && <p className="pc-help">Nenhuma movimentação registrada.</p>}</>}</>}
 {aba === 'fiscal' && <><div className="pc-info"><strong>{fiscalProduto({ ncm: campos.ncm, cfop: campos.cfop, icmsSituacao: campos.icmsSituacao, unidade: campos.unidade, cest: campos.cest, nome: '', preco: 0, ativo: true, id: '' })}</strong><span>Você pode usar o padrão da loja ou informar códigos específicos para este produto.</span></div><div className="pc-field-grid">{input('ncm', 'NCM', { numeric: true, limite: 8, ajuda: '8 dígitos', placeholder: 'Ex.: 30049099' })}{input('cest', 'CEST', { numeric: true, limite: 7, ajuda: '7 dígitos, quando aplicável' })}{input('cfop', 'CFOP de saída', { numeric: true, limite: 4, placeholder: 'Ex.: 5102' })}{input('icmsSituacao', 'CSOSN / CST', { numeric: true, limite: 3, placeholder: 'Ex.: 102' })}{input('unidade', 'Unidade comercial', { limite: 6, placeholder: 'UN, CX, KG…' })}</div></>}
 {aba === 'publicacao' && <><div className="pc-field-grid"><Campo nome="situacao" titulo="Situação do cadastro"><select id="pc-situacao" value={situacao} disabled={ocupado} onChange={e => { setSituacao(e.target.value as typeof situacao); if (e.target.value !== 'ativo') setVisivel(false); }}>{Object.entries(rotulos).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></Campo><div className="pc-field"><label className="pc-switch"><input type="checkbox" checked={visivel} disabled={situacao !== 'ativo' || ocupado} onChange={e => setVisivel(e.target.checked)} />Publicar na vitrine</label><small>{situacao === 'ativo' ? 'Pode estar ativo no cadastro e oculto na vitrine.' : 'Ative o cadastro para permitir a publicação.'}</small>{erros.publicado && <span className="pc-field-error">{erros.publicado}</span>}</div>{input('seoTitulo', 'Título para busca', { limite: 70, largo: true, ajuda: `${campos.seoTitulo.length} / 70 caracteres. Opcional para integrações de busca.` })}{input('seoDescricao', 'Resumo para busca', { limite: 160, largo: true, area: true, ajuda: `${campos.seoDescricao.length} / 160 caracteres. Opcional para integrações de busca.` })}</div><div className="pc-info"><strong>Cadastro: {rotulos[situacao]} · Vitrine: {visivel ? 'Publicado' : 'Oculto'}</strong><span>Arquivar preserva o saldo e o histórico, retirando o produto das vendas.</span></div></>}
 {aba === 'historico' && <>{historicoCarregando ? <p>Carregando histórico…</p> : historicoErro ? <p role="alert">{historicoErro}</p> : !historico.length ? <p className="pc-help">As novas alterações passam a ser registradas a partir desta atualização.</p> : historico.map(h => <article className="pc-history-item" key={h.id}><strong>{h.acao}</strong><span>{new Date(h.criadoEm).toLocaleString('pt-BR')} · {h.autor}</span><details><summary>Ver dados salvos</summary><dl><dt>Código interno</dt><dd>{h.dados.codigoInterno || '—'}</dd><dt>Nome</dt><dd>{h.dados.nome}</dd><dt>Preço</dt><dd>{moeda(h.dados.preco)}</dd><dt>Promoção</dt><dd>{h.dados.precoPromocional ? moeda(h.dados.precoPromocional) : '—'}</dd><dt>Cadastro / vitrine</dt><dd>{rotulos[situacaoProduto(h.dados)]} / {publicado(h.dados) ? 'Publicado' : 'Oculto'}</dd><dt>NCM / CFOP</dt><dd>{h.dados.ncm || 'Padrão da loja'} / {h.dados.cfop || 'Padrão da loja'}</dd></dl></details></article>)}</>}
 </section><aside className="pc-preview"><span className="pc-eyebrow">PRÉVIA DO PRODUTO</span><div className="pc-preview-photo"><Foto url={galeria[0]} backend={backendUrl} nome={campos.nome || 'Produto'} /></div><small>{campos.marca || campos.categoria || 'Seu catálogo'}</small><h3>{campos.nome || 'Nome do produto'}</h3><p>{campos.descricao || 'A descrição aparecerá aqui.'}</p>{campos.precoPromocional && <del>{moeda(numero(campos.preco) || 0)}</del>}<strong className="pc-preview-price">{moeda(numero(campos.precoPromocional || campos.preco) || 0)}</strong><hr /><span className={`pc-dot ${visivel ? 'pc-dot-green' : ''}`}>{visivel ? 'Publicado na vitrine' : 'Oculto da vitrine'}</span><small>Salve para aplicar os dados preenchidos.</small></aside></div>
 <footer className="pc-savebar"><span>{dirty ? 'Você tem alterações não salvas' : 'Nenhuma alteração pendente'}{upload && ' · Enviando fotos'}</span><button type="button" className="pc-btn" disabled={ocupado || upload} onClick={voltar}>Cancelar</button><button type="submit" className="pc-btn pc-btn-primary" disabled={ocupado || upload}>{ocupado ? 'Salvando…' : id ? 'Salvar alterações' : 'Salvar produto'}</button></footer>
 </form>}
 {importacao && <div className="pc-dialog-overlay"><section id="pc-import-dialog" onKeyDown={tecladoImportacao} role="dialog" aria-modal="true" aria-labelledby="pc-import-title" className="pc-import-dialog"><header><div><span className="pc-eyebrow">IMPORTAÇÃO DE CATÁLOGO</span><h3 id="pc-import-title">Importar produtos</h3></div><button type="button" className="pc-btn" disabled={ocupado} aria-label="Fechar importação" onClick={() => { setImportacao(false); setPrevia(null); setErro(''); }}>×</button></header><p>Use um CSV do Excel com até 500 produtos. O código interno identifica os cadastros que serão atualizados. Confira a prévia antes de aplicar.</p><button className="pc-btn" type="button" onClick={() => baixarCsv('modelo-produtos.csv', gerarCsv([{ codigoInterno: 'MED-001', nome: 'Produto de exemplo', preco: 19.9, situacao: 'rascunho', publicado: false }]))}>Baixar modelo</button><button className="pc-dropzone" type="button" disabled={ocupado} onClick={() => arquivoInput.current?.click()}><Icone nome="upload" size={28} /><strong>{ocupado ? 'Validando arquivo…' : 'Selecionar arquivo CSV'}</strong><span>Os dados são validados antes de salvar qualquer produto.</span></button><input ref={arquivoInput} type="file" accept=".csv,.tsv,text/csv" hidden onChange={e => void importar(e.target.files?.[0])} />{erro && <div className="pc-notice pc-notice-error" role="alert">{erro}</div>}{previa && <><div className="pc-price-summary"><div><small>Novos produtos</small><strong>{previa.resumo.novos}</strong></div><div><small>Atualizações</small><strong>{previa.resumo.atualizados}</strong></div></div><div className="pc-import-preview">{previa.produtos.slice(0, 10).map(p => <div key={p.id}><span>{p.codigoInterno} · {p.nome}</span><strong>{moeda(p.preco)}</strong></div>)}{previa.produtos.length > 10 && <p>Mais {previa.produtos.length - 10} produtos no arquivo.</p>}</div><p className="pc-help">Confirmação salva todo o arquivo em uma única operação. Se houver erro, nenhum produto desta importação é salvo.</p></>}<footer><button type="button" className="pc-btn" disabled={ocupado} onClick={() => { setImportacao(false); setPrevia(null); }}>Cancelar</button><button type="button" className="pc-btn pc-btn-primary" disabled={ocupado || !previa} onClick={() => void confirmarImportacao()}>{ocupado ? 'Importando…' : `Confirmar importação${previa ? ` de ${previa.resumo.total} produtos` : ''}`}</button></footer></section></div>}
 </div>;
}
