// Descrição funcional de cada tabela/coluna do banco do Distre.
// Usado por gerar-doc-banco.cjs para montar o README e o schema-completo.sql.
module.exports = {
  tabelas: {
    EMPRESAS: 'Empresas/redes clientes do Distre (multi-tenant). Uma empresa tem várias lojas.',
    LOJAS: 'Lojas (filiais) de cada empresa. Cada loja tem login próprio no painel e cardápio/vitrine própria.',
    ADMINISTRADORES: 'Usuários administradores master do painel (senha com hash bcrypt).',
    SESSOES: 'Sessões de login persistidas (sobrevivem a reinício do servidor).',
    MOTORISTAS: 'Entregadores (motoboys) vinculados a uma loja e ao app do entregador.',
    TIPOS_VEICULOS: 'Catálogo de tipos de veículo da frota.',
    ENTREGAS: 'Comandas: pedidos (tipo "pedido") e entregas (tipo "entrega") com todo o ciclo de vida, rota, telemetria e comprovante (POD).',
    LOGS_EVENTOS: 'Log de todas as mensagens que passam pelo barramento de eventos (broker).',
    PRODUTOS: 'Produtos do cardápio/vitrine de cada loja, com dados fiscais opcionais por produto.',
    PLANOS: 'Planos de assinatura do SaaS (Bronze, Silver, Gold, Enterprise) e seus limites.',
    ASSINATURAS_EMPRESAS: 'Assinatura de cada empresa/loja a um plano (máquina de estados de cobrança).',
    FATURAS: 'Faturas mensais da assinatura (Pix/boleto/cartão via gateway de pagamento).',
    HISTORICO_PAGAMENTOS: 'Transações de pagamento registradas para cada fatura.',
    CONFIGURACOES_COBRANCA: 'Parâmetros globais da régua de cobrança (dunning): carência, multa, juros, avisos.',
    LEDGER_FINANCEIRO: 'Razão financeiro imutável (append-only, encadeado por hash). Trigger bloqueia UPDATE/DELETE.',
    WEBHOOK_EVENTS: 'Webhooks recebidos do gateway de pagamento (ingestão idempotente + fila de reprocessamento).',
    CONFIG_FISCAL_LOJA: 'Dados fiscais do emitente por loja (CNPJ, IE, endereço, provedor, ambiente, séries, tributação padrão).',
    CREDENCIAIS_FISCAIS: 'Segredos fiscais por loja — certificado A1, senha, CSC e tokens da Focus NFe — TODOS CIFRADOS (AES-256-GCM).',
    NOTAS_FISCAIS: 'NFC-e (modelo 65) e NF-e (modelo 55) emitidas, com chave, protocolo, status e o snapshot completo do documento.',
    ESTOQUE_SALDOS: 'Saldo físico de cada produto por loja. Só existe linha para produtos com controle de estoque (após o 1º recebimento); sem linha = "Sem controle". SALDO nunca fica negativo (CHECK).',
    ESTOQUE_MOVIMENTOS: 'Extrato do estoque: toda entrada, venda, estorno e ajuste. A chave de idempotência impede lançar o mesmo evento duas vezes.',
    PEDIDO_CONFERENCIA_ITENS: 'Itens de cada pedido a conferir na separação (por produto), com a quantidade pedida e quantas unidades já foram lidas pelo EAN.',
    PEDIDO_CONFERENCIA_LEITURAS: 'Leituras de código de barras da conferência. A chave torna a leitura idempotente: o mesmo envio repetido não conta duas vezes.',
    PEDIDO_CONFERENCIA_FALTAS: 'Produtos que faltaram na separação: o que saiu do pedido (ou o motivo do cancelamento), quantas unidades, por quê e o desfecho. Auditoria da tela "Em falta".',
  },
  colunas: {
    // ESTOQUE
    'ESTOQUE_SALDOS.LOJA_ID': 'Loja dona do saldo.',
    'ESTOQUE_SALDOS.PRODUTO_ID': 'Produto (→ PRODUTOS.ID).',
    'ESTOQUE_SALDOS.SALDO': 'Unidades disponíveis para venda (>= 0).',
    'ESTOQUE_MOVIMENTOS.ID': 'Sequência auto-incremento do extrato.',
    'ESTOQUE_MOVIMENTOS.LOJA_ID': 'Loja do movimento.',
    'ESTOQUE_MOVIMENTOS.PRODUTO_ID': 'Produto movimentado.',
    'ESTOQUE_MOVIMENTOS.TIPO': 'ENTRADA (recebimento, soma) | VENDA (baixa na vitrine) | ESTORNO (devolve ao saldo: cancelamento ou item em falta) | AJUSTE (correção de inventário, ex.: saldo zerado por falta).',
    'ESTOQUE_MOVIMENTOS.QUANTIDADE': 'Unidades do movimento (sempre positivo; o sentido vem do TIPO).',
    'ESTOQUE_MOVIMENTOS.REFERENCIA': 'Documento/pedido de origem (ex.: COMANDA-0012, NF de entrada). Os estornos de um pedido usam o id do pedido aqui.',
    'ESTOQUE_MOVIMENTOS.CHAVE': 'Chave de idempotência: id do pedido (VENDA/ESTORNO) ou chave do recebimento. Única por loja + produto + tipo.',
    'ESTOQUE_MOVIMENTOS.CRIADO_EM': 'Momento do lançamento (UTC).',
    // CONFERÊNCIA
    'PEDIDO_CONFERENCIA_ITENS.PEDIDO_ID': 'Pedido (→ ENTREGAS.ID).',
    'PEDIDO_CONFERENCIA_ITENS.PRODUTO_ID': 'Produto do item.',
    'PEDIDO_CONFERENCIA_ITENS.NOME': 'Nome do produto no momento da venda.',
    'PEDIDO_CONFERENCIA_ITENS.EAN': 'Código de barras esperado na leitura.',
    'PEDIDO_CONFERENCIA_ITENS.QUANTIDADE': 'Unidades que o pedido ainda tem deste produto (diminui quando faltam unidades).',
    'PEDIDO_CONFERENCIA_ITENS.CONFERIDA': 'Unidades já lidas pelo EAN (nunca passa de QUANTIDADE).',
    'PEDIDO_CONFERENCIA_ITENS.PRECO': 'Preço unitário cobrado na venda; base para recalcular o total quando um item falta. Vazio em pedidos antigos.',
    'PEDIDO_CONFERENCIA_LEITURAS.PEDIDO_ID': 'Pedido conferido.',
    'PEDIDO_CONFERENCIA_LEITURAS.CHAVE': 'Chave de idempotência da leitura (única por pedido).',
    'PEDIDO_CONFERENCIA_LEITURAS.EAN': 'Código lido.',
    'PEDIDO_CONFERENCIA_LEITURAS.CRIADO_EM': 'Momento da leitura (UTC).',
    'PEDIDO_CONFERENCIA_FALTAS.ID': 'Sequência auto-incremento.',
    'PEDIDO_CONFERENCIA_FALTAS.PEDIDO_ID': 'Pedido onde faltou produto.',
    'PEDIDO_CONFERENCIA_FALTAS.PRODUTO_ID': 'Produto que faltou.',
    'PEDIDO_CONFERENCIA_FALTAS.NOME': 'Nome do produto.',
    'PEDIDO_CONFERENCIA_FALTAS.QUANTIDADE': 'Unidades que faltaram.',
    'PEDIDO_CONFERENCIA_FALTAS.PRECO': 'Preço unitário no momento (para saber o quanto o total diminuiu).',
    'PEDIDO_CONFERENCIA_FALTAS.MOTIVO': 'Motivo informado pelo operador (+ observação opcional).',
    'PEDIDO_CONFERENCIA_FALTAS.DESFECHO': 'ITEM_REMOVIDO (pedido segue sem o item) | PEDIDO_CANCELADO (pedido inteiro cancelado).',
    'PEDIDO_CONFERENCIA_FALTAS.CHAVE': 'Chave de idempotência da operação (única por pedido): repetir o envio não aplica duas vezes.',
    'PEDIDO_CONFERENCIA_FALTAS.CRIADO_EM': 'Momento do registro (UTC).',
    // PRODUTOS (cadastro ampliado)
    // EMPRESAS
    'EMPRESAS.ID': 'Identificador da empresa (UUID).',
    'EMPRESAS.NOME': 'Nome/razão da empresa.',
    'EMPRESAS.CNPJ': 'CNPJ da empresa (único).',
    'EMPRESAS.TELEFONE': 'Telefone de contato — aparece na vitrine (WhatsApp/ligação).',
    'EMPRESAS.EMAIL': 'E-mail de contato.',
    'EMPRESAS.ATIVO': '1 = ativa; 0 = desativada (bloqueia login das lojas).',
    'EMPRESAS.CRIADO_EM': 'Data de cadastro (ISO 8601).',
    'EMPRESAS.STATUS_FINANCEIRO': 'REGULAR | INADIMPLENTE | SUSPENSO | CANCELADO.',
    // LOJAS
    'LOJAS.ID': 'Identificador da loja (UUID) — usado no link da vitrine /loja/<ID>.',
    'LOJAS.EMPRESA_ID': 'Empresa dona da loja (FK → EMPRESAS.ID).',
    'LOJAS.NOME': 'Nome exibido no painel e na vitrine.',
    'LOJAS.CNPJ': 'CNPJ da loja (único quando informado — índice filtrado).',
    'LOJAS.ENDERECO': 'Logradouro.',
    'LOJAS.NUMERO': 'Número do endereço.',
    'LOJAS.BAIRRO': 'Bairro.',
    'LOJAS.CIDADE': 'Cidade.',
    'LOJAS.UF': 'Estado (sigla).',
    'LOJAS.CEP': 'CEP.',
    'LOJAS.USUARIO': 'Login da loja no painel (único).',
    'LOJAS.SENHA_HASH': 'Hash bcrypt da senha da loja.',
    'LOJAS.CHAVE_ACESSO': 'Chave DISTRE-XXXX-YYYY-ZZZZ (única) — também é a API key de integração (X-Api-Key).',
    'LOJAS.ATIVO': '1 = ativa; 0 = bloqueada.',
    'LOJAS.CRIADO_EM': 'Data de cadastro.',
    'LOJAS.RECEBE_PEDIDOS': '1 = pedidos da vitrine entram como "pedido" (Novos → Separação); 0 = entram direto como entrega.',
    'LOJAS.LATITUDE': 'Latitude da loja (geocodificada pelo endereço/CEP ou GPS).',
    'LOJAS.LONGITUDE': 'Longitude da loja.',
    'LOJAS.STATUS_FINANCEIRO': 'Situação da cobrança desta loja (REGULAR/INADIMPLENTE/SUSPENSO/CANCELADO).',
    'LOJAS.LOGO_URL': 'Logomarca exibida na vitrine (/uploads/...).',
    // ADMINISTRADORES / SESSOES
    'ADMINISTRADORES.USUARIO': 'Login do administrador master.',
    'ADMINISTRADORES.SENHA_HASH': 'Hash bcrypt da senha.',
    'SESSOES.TOKEN': 'Token Bearer da sessão.',
    'SESSOES.TIPO': 'admin | loja.',
    'SESSOES.LOJA_ID': 'Loja da sessão (quando tipo = loja).',
    'SESSOES.NOME_LOJA': 'Nome da loja (cache para o painel).',
    'SESSOES.NOME_EMPRESA': 'Nome da empresa (cache para o painel).',
    'SESSOES.RECEBE_PEDIDOS': 'Cópia de LOJAS.RECEBE_PEDIDOS no login.',
    'SESSOES.LATITUDE': 'Latitude da loja no login.',
    'SESSOES.LONGITUDE': 'Longitude da loja no login.',
    'SESSOES.CRIADO_EM': 'Início da sessão.',
    'SESSOES.EXPIRA_EM': 'Expiração da sessão.',
    // MOTORISTAS / TIPOS_VEICULOS
    'MOTORISTAS.ID': 'Identificador do entregador.',
    'MOTORISTAS.NOME': 'Nome do entregador.',
    'MOTORISTAS.TIPO_VEICULO': 'Tipo de veículo (→ TIPOS_VEICULOS.ID).',
    'MOTORISTAS.STATUS': 'ocioso | ocupado.',
    'MOTORISTAS.LOJA_ID': 'Loja à qual o entregador pertence.',
    'MOTORISTAS.CODIGO_VINCULO': 'Código de 6 dígitos para parear o app do entregador (único).',
    'MOTORISTAS.DISPOSITIVO_CONECTADO': '1 = app do entregador online.',
    'MOTORISTAS.X': 'Posição na grade 0–100 (legado da simulação).',
    'MOTORISTAS.Y': 'Posição na grade 0–100 (legado da simulação).',
    'MOTORISTAS.ULTIMA_ATUALIZACAO': 'Último ping de GPS.',
    'TIPOS_VEICULOS.ID': 'Código do tipo (ex.: motorcycle).',
    'TIPOS_VEICULOS.NOME': 'Nome exibido (ex.: Motocicleta).',
    // ENTREGAS
    'ENTREGAS.ID': 'Número da comanda (ex.: COMANDA-0012).',
    'ENTREGAS.NOME_CLIENTE': 'Cliente final.',
    'ENTREGAS.ENDERECO': 'Endereço de entrega completo (texto).',
    'ENTREGAS.ITENS': 'Itens em JSON (array de strings "2x Produto (obs)").',
    'ENTREGAS.PRIORIDADE': 'baixa | media | alta | critica.',
    'ENTREGAS.TIPO_CARGA': 'normal | expressa | agendado.',
    'ENTREGAS.STATUS': 'RECEBIDO, EM_PREPARO, DESPACHADO, EM_TRANSITO, NO_LOCAL, ENTREGUE, RECUSADO_INSUCESSO, ALERTA_INCIDENTE, AGUARDANDO_RETORNO_CD, PRODUTO_RETORNADO_ESTOQUE, SLA_ALERTA, CANCELADO.',
    'ENTREGAS.MOTORISTA': 'Entregador atribuído (JSON).',
    'ENTREGAS.ROTA': 'Rota planejada: distância, duração, custo e pontos (JSON).',
    'ENTREGAS.TELEMETRIA': 'Última telemetria: velocidade, posição, temperatura (JSON).',
    'ENTREGAS.INCIDENTES': 'Incidentes/alertas da entrega (JSON).',
    'ENTREGAS.URL_WEBHOOK': 'URL notificada a cada mudança de status.',
    'ENTREGAS.LOGS_WEBHOOK': 'Tentativas de webhook (JSON) — retentativas com backoff.',
    'ENTREGAS.CRIADO_EM': 'Data de criação (ISO 8601).',
    'ENTREGAS.ATUALIZADO_EM': 'Última alteração.',
    'ENTREGAS.RECEBEDOR_NOME': 'POD: nome de quem recebeu.',
    'ENTREGAS.RECEBEDOR_CPF': 'POD: CPF de quem recebeu.',
    'ENTREGAS.COMPROVANTE_FOTO_URL': 'POD: foto do canhoto/fachada.',
    'ENTREGAS.ASSINATURA_BASE64': 'POD: assinatura digital (imagem base64).',
    'ENTREGAS.JUSTIFICATIVA_DESVIO_COORDENADA': 'Justificativa quando a entrega foi confirmada fora da cerca virtual.',
    'ENTREGAS.DATA_HORA_CONCLUSAO': 'Fechamento da entrega (usado no rollback de 60s).',
    'ENTREGAS.SEQUENCIA_ESPERADA': 'Ordem planejada na rota do entregador.',
    'ENTREGAS.SEQUENCIA_REALIZADA': 'Ordem em que foi de fato entregue (detecta "rota pulada").',
    'ENTREGAS.VALOR': 'Valor total da venda.',
    'ENTREGAS.LOJA_ID': 'Loja dona da comanda.',
    'ENTREGAS.NOME_LOJA': 'Nome da loja (cópia).',
    'ENTREGAS.NOME_EMPRESA': 'Nome da empresa (cópia).',
    'ENTREGAS.CLIENTE_DOCUMENTO': 'CPF/CNPJ do cliente (opcional; usado na nota fiscal).',
    'ENTREGAS.ROMANEIO_ID': 'Romaneio (lote de despacho) da entrega.',
    'ENTREGAS.BAIRRO': 'Bairro de entrega.',
    'ENTREGAS.CIDADE': 'Cidade de entrega.',
    'ENTREGAS.FORMA_PAGAMENTO': 'maquininha | pix | dinheiro.',
    'ENTREGAS.DESPACHADO_EM': 'Momento do despacho.',
    'ENTREGAS.TIPO_COMANDA': 'pedido (vitrine/WhatsApp, passa por separação) | entrega.',
    'ENTREGAS.REFERENCIA': 'Observações; "Origem: Pedido X" liga a entrega ao pedido de origem.',
    'ENTREGAS.DESTINO_LAT': 'Latitude real do destino (geocodificada).',
    'ENTREGAS.DESTINO_LNG': 'Longitude real do destino.',
    // LOGS_EVENTOS
    'LOGS_EVENTOS.ID': 'Identificador do evento (UUID).',
    'LOGS_EVENTOS.TOPICO': 'Tópico do barramento (ex.: entrega.recebida, entrega.monitorada).',
    'LOGS_EVENTOS.ENTREGA_ID': 'Comanda relacionada.',
    'LOGS_EVENTOS.CONTEUDO': 'Payload do evento (JSON).',
    'LOGS_EVENTOS.TIMESTAMP_REGISTRO': 'Momento do registro.',
    // PRODUTOS
    'PRODUTOS.ID': 'Identificador (prod-xxxxxxxxxx).',
    'PRODUTOS.NOME': 'Nome exibido na vitrine.',
    'PRODUTOS.PRECO': 'Preço de venda.',
    'PRODUTOS.LOJA_ID': 'Loja dona do produto (NULL = produto global de demonstração).',
    'PRODUTOS.ATIVO': '1 = aparece na vitrine; 0 = oculto.',
    'PRODUTOS.IMAGEM_URL': 'Foto do produto (/uploads/... ou URL externa).',
    'PRODUTOS.DESCRICAO': 'Subtítulo/descrição no card (ex.: "20 comprimidos").',
    'PRODUTOS.CATEGORIA': 'Categoria livre (gera a sidebar e os blocos da vitrine).',
    'PRODUTOS.SUBCATEGORIA': 'Subcategoria opcional.',
    'PRODUTOS.NCM': 'Fiscal: NCM (8 dígitos). Vazio = NCM padrão da loja.',
    'PRODUTOS.CEST': 'Fiscal: CEST (7 dígitos), quando há substituição tributária.',
    'PRODUTOS.CFOP': 'Fiscal: CFOP do produto. Vazio = padrão da loja.',
    'PRODUTOS.ICMS_SITUACAO': 'Fiscal: CSOSN (Simples) ou CST (Regime Normal). Vazio = padrão da loja.',
    'PRODUTOS.UNIDADE': 'Fiscal: unidade comercial (UN, CX, KG...). Vazio = UN.',
    'PRODUTOS.CODIGO_BARRAS': 'Fiscal: GTIN/EAN. Vazio = "SEM GTIN" na nota.',
    // PLANOS / ASSINATURAS / FATURAS / PAGAMENTOS / COBRANÇA
    'PLANOS.ID': 'Código do plano (bronze, silver, gold, enterprise).',
    'PLANOS.NOME': 'Nome do plano.',
    'PLANOS.DESCRICAO': 'Descrição comercial.',
    'PLANOS.VALOR_MENSAL': 'Mensalidade.',
    'PLANOS.LIMITE_ENTREGAS_MES': 'Teto de entregas/mês (NULL = ilimitado).',
    'PLANOS.LIMITE_LOJAS': 'Teto de lojas (NULL = ilimitado).',
    'PLANOS.LIMITE_MOTORISTAS': 'Teto de motoristas (NULL = ilimitado).',
    'PLANOS.ATIVO': '1 = plano disponível.',
    'PLANOS.CRIADO_EM': 'Data de cadastro.',
    'ASSINATURAS_EMPRESAS.ID': 'Identificador da assinatura.',
    'ASSINATURAS_EMPRESAS.EMPRESA_ID': 'Empresa (FK → EMPRESAS.ID).',
    'ASSINATURAS_EMPRESAS.PLANO_ID': 'Plano contratado (FK → PLANOS.ID).',
    'ASSINATURAS_EMPRESAS.STATUS': 'Estado da assinatura (TRIAL, ATIVA, INADIMPLENTE, SUSPENSA, CANCELADA...).',
    'ASSINATURAS_EMPRESAS.DIA_VENCIMENTO': 'Dia do mês de vencimento.',
    'ASSINATURAS_EMPRESAS.VALOR_PERSONALIZADO': 'Valor negociado (sobrepõe o do plano).',
    'ASSINATURAS_EMPRESAS.PROXIMO_FATURAMENTO': 'Próxima geração de fatura.',
    'ASSINATURAS_EMPRESAS.CRIADO_EM': 'Início da assinatura.',
    'ASSINATURAS_EMPRESAS.CANCELADO_EM': 'Data de cancelamento.',
    'ASSINATURAS_EMPRESAS.TRIAL_EXPIRA_EM': 'Fim do período de teste.',
    'ASSINATURAS_EMPRESAS.GATEWAY_SUBSCRIPTION_ID': 'ID da assinatura no gateway (Asaas).',
    'ASSINATURAS_EMPRESAS.METODO_PAGAMENTO_PADRAO': 'PIX | BOLETO | CARTAO.',
    'ASSINATURAS_EMPRESAS.SUSPENSA_EM': 'Quando foi suspensa por inadimplência.',
    'ASSINATURAS_EMPRESAS.LOJA_ID': 'Loja cobrada (cobrança por loja).',
    'FATURAS.ID': 'Identificador da fatura.',
    'FATURAS.EMPRESA_ID': 'Empresa (FK → EMPRESAS.ID).',
    'FATURAS.ASSINATURAS_EMPRESAS_ID': 'Assinatura que gerou a fatura.',
    'FATURAS.VALOR_BRUTO': 'Valor cobrado.',
    'FATURAS.VALOR_DESCONTO': 'Desconto concedido.',
    'FATURAS.STATUS': 'PENDENTE | PAGA | VENCIDA | CANCELADA.',
    'FATURAS.DATA_EMISSAO': 'Emissão.',
    'FATURAS.DATA_VENCIMENTO': 'Vencimento.',
    'FATURAS.DATA_PAGAMENTO': 'Pagamento (baixa).',
    'FATURAS.REFERENCIA_MES_ANO': 'Competência (MM/AAAA).',
    'FATURAS.GATEWAY_FATURA_ID': 'ID da cobrança no gateway.',
    'FATURAS.BOLETO_URL': 'Link do boleto.',
    'FATURAS.PIX_COPIA_COLA': 'Código Pix copia-e-cola.',
    'FATURAS.CRIADO_EM': 'Data de criação.',
    'FATURAS.METODO_PAGAMENTO': 'PIX | BOLETO | CARTAO.',
    'FATURAS.TENTATIVAS_COBRANCA': 'Tentativas de cobrança (régua de dunning).',
    'FATURAS.PROXIMA_ACAO_DUNNING': 'Próximo passo agendado da régua.',
    'FATURAS.LOJA_ID': 'Loja cobrada.',
    'HISTORICO_PAGAMENTOS.ID': 'Identificador da transação.',
    'HISTORICO_PAGAMENTOS.FATURA_ID': 'Fatura paga.',
    'HISTORICO_PAGAMENTOS.METODO_PAGAMENTO': 'Meio de pagamento.',
    'HISTORICO_PAGAMENTOS.VALOR_PAGO': 'Valor recebido.',
    'HISTORICO_PAGAMENTOS.DATA_TRANSACAO': 'Data da transação.',
    'HISTORICO_PAGAMENTOS.STATUS_TRANSACAO': 'Resultado da transação.',
    'HISTORICO_PAGAMENTOS.GATEWAY_TRANSACAO_ID': 'ID no gateway.',
    'HISTORICO_PAGAMENTOS.LOG_TRANSACAO': 'Retorno bruto do gateway (JSON).',
    'CONFIGURACOES_COBRANCA.ID': 'Sempre "default" (linha única).',
    'CONFIGURACOES_COBRANCA.DIAS_CARENCIA_BLOQUEIO': 'Dias após o vencimento até bloquear a loja.',
    'CONFIGURACOES_COBRANCA.MULTA_PERCENTUAL': 'Multa por atraso (%).',
    'CONFIGURACOES_COBRANCA.JUROS_MES_PERCENTUAL': 'Juros ao mês (%).',
    'CONFIGURACOES_COBRANCA.EMAIL_NOTIFICACAO_DIAS_ANTES': 'Aviso por e-mail N dias antes do vencimento.',
    'CONFIGURACOES_COBRANCA.WHATSAPP_NOTIFICACAO_DIAS_ATRASO': 'Aviso por WhatsApp N dias após o atraso.',
    // LEDGER / WEBHOOKS
    'LEDGER_FINANCEIRO.SEQ': 'Sequência auto-incremento (ordem do razão).',
    'LEDGER_FINANCEIRO.ID': 'Identificador do lançamento (único).',
    'LEDGER_FINANCEIRO.EMPRESA_ID': 'Empresa do lançamento.',
    'LEDGER_FINANCEIRO.ASSINATURA_ID': 'Assinatura relacionada.',
    'LEDGER_FINANCEIRO.FATURA_ID': 'Fatura relacionada.',
    'LEDGER_FINANCEIRO.TIPO_LANCAMENTO': 'Tipo (ex.: FATURA_EMITIDA, PAGAMENTO_RECEBIDO, ESTORNO).',
    'LEDGER_FINANCEIRO.VALOR': 'Valor do lançamento.',
    'LEDGER_FINANCEIRO.MOEDA': 'Moeda (BRL).',
    'LEDGER_FINANCEIRO.ORIGEM': 'Quem originou (webhook, rotina, manual...).',
    'LEDGER_FINANCEIRO.REFERENCIA_EXTERNA': 'ID externo (gateway).',
    'LEDGER_FINANCEIRO.METADADOS': 'Detalhes (JSON).',
    'LEDGER_FINANCEIRO.HASH_ANTERIOR': 'Hash do lançamento anterior (encadeamento).',
    'LEDGER_FINANCEIRO.HASH_ATUAL': 'SHA-256 deste lançamento + anterior (detecta adulteração).',
    'LEDGER_FINANCEIRO.CRIADO_EM': 'Momento do lançamento.',
    'LEDGER_FINANCEIRO.CRIADO_POR': 'Autor (sistema/usuário).',
    'WEBHOOK_EVENTS.ID': 'Identificador interno.',
    'WEBHOOK_EVENTS.GATEWAY_EVENT_ID': 'ID do evento no gateway (idempotência).',
    'WEBHOOK_EVENTS.GATEWAY': 'Gateway de origem (ASAAS, MOCK...).',
    'WEBHOOK_EVENTS.EVENT_TYPE': 'Tipo normalizado (payment.confirmed etc.).',
    'WEBHOOK_EVENTS.PAYLOAD': 'Corpo bruto recebido.',
    'WEBHOOK_EVENTS.ASSINATURA_HMAC': 'Assinatura/token recebido para validação.',
    'WEBHOOK_EVENTS.STATUS': 'PENDENTE | PROCESSADO | ERRO | DLQ.',
    'WEBHOOK_EVENTS.TENTATIVAS': 'Tentativas de processamento.',
    'WEBHOOK_EVENTS.PROXIMA_TENTATIVA': 'Próximo reprocessamento (backoff).',
    'WEBHOOK_EVENTS.ERRO_ULTIMO': 'Último erro.',
    'WEBHOOK_EVENTS.RECEBIDO_EM': 'Recebimento.',
    'WEBHOOK_EVENTS.PROCESSADO_EM': 'Processamento concluído.',
    // FISCAL
    'CONFIG_FISCAL_LOJA.LOJA_ID': 'Loja (uma configuração por loja).',
    'CONFIG_FISCAL_LOJA.RAZAO_SOCIAL': 'Razão social do emitente.',
    'CONFIG_FISCAL_LOJA.NOME_FANTASIA': 'Nome fantasia.',
    'CONFIG_FISCAL_LOJA.CNPJ': 'CNPJ do emitente (só dígitos).',
    'CONFIG_FISCAL_LOJA.INSCRICAO_ESTADUAL': 'IE (só dígitos) ou "ISENTO".',
    'CONFIG_FISCAL_LOJA.REGIME_TRIBUTARIO': '1 Simples Nacional | 2 Simples (excesso de sublimite) | 3 Regime Normal.',
    'CONFIG_FISCAL_LOJA.LOGRADOURO': 'Endereço do emitente.',
    'CONFIG_FISCAL_LOJA.NUMERO': 'Número.',
    'CONFIG_FISCAL_LOJA.BAIRRO': 'Bairro.',
    'CONFIG_FISCAL_LOJA.MUNICIPIO': 'Município.',
    'CONFIG_FISCAL_LOJA.UF': 'UF (define o código da UF na chave de acesso).',
    'CONFIG_FISCAL_LOJA.CEP': 'CEP (só dígitos).',
    'CONFIG_FISCAL_LOJA.TELEFONE': 'Telefone do emitente.',
    'CONFIG_FISCAL_LOJA.AMBIENTE': 'HOMOLOGACAO | PRODUCAO.',
    'CONFIG_FISCAL_LOJA.SERIE_NFCE': 'Série da NFC-e.',
    'CONFIG_FISCAL_LOJA.PROXIMO_NUMERO_NFCE': 'Próximo número da NFC-e (reserva atômica; nunca retrocede).',
    'CONFIG_FISCAL_LOJA.SERIE_NFE': 'Série da NF-e.',
    'CONFIG_FISCAL_LOJA.PROXIMO_NUMERO_NFE': 'Próximo número da NF-e.',
    'CONFIG_FISCAL_LOJA.NCM_PADRAO': 'NCM usado nos itens sem NCM próprio.',
    'CONFIG_FISCAL_LOJA.CFOP_PADRAO': 'CFOP padrão (ex.: 5102).',
    'CONFIG_FISCAL_LOJA.ICMS_SITUACAO_PADRAO': 'CSOSN/CST padrão (ex.: 102).',
    'CONFIG_FISCAL_LOJA.ORIGEM_PADRAO': 'Origem da mercadoria (0 = nacional).',
    'CONFIG_FISCAL_LOJA.TOKEN_PROVEDOR': 'LEGADO — não é mais usado (tokens ficam cifrados em CREDENCIAIS_FISCAIS).',
    'CONFIG_FISCAL_LOJA.ATUALIZADO_EM': 'Última alteração.',
    'CONFIG_FISCAL_LOJA.PROVEDOR': 'SIMULADO (sem valor fiscal) | FOCUSNFE (emissão real).',
    'CONFIG_FISCAL_LOJA.PERCENTUAL_TRIBUTOS': 'Tributos aproximados % (Lei 12.741/IBPT) impressos na nota.',
    'CONFIG_FISCAL_LOJA.EMAIL': 'E-mail do emitente.',
    'CREDENCIAIS_FISCAIS.LOJA_ID': 'Loja dona das credenciais.',
    'CREDENCIAIS_FISCAIS.CERT_PFX': 'CIFRADO — arquivo do certificado A1 (.pfx).',
    'CREDENCIAIS_FISCAIS.CERT_SENHA': 'CIFRADO — senha do certificado.',
    'CREDENCIAIS_FISCAIS.CERT_TITULAR': 'Titular lido do certificado (aberto).',
    'CREDENCIAIS_FISCAIS.CERT_CNPJ': 'CNPJ lido do certificado (aberto).',
    'CREDENCIAIS_FISCAIS.CERT_VALIDO_ATE': 'Validade do certificado (aberto).',
    'CREDENCIAIS_FISCAIS.CSC_ID_HOMOLOGACAO': 'ID do CSC de homologação.',
    'CREDENCIAIS_FISCAIS.CSC_HOMOLOGACAO': 'CIFRADO — CSC (token NFC-e) de homologação.',
    'CREDENCIAIS_FISCAIS.CSC_ID_PRODUCAO': 'ID do CSC de produção.',
    'CREDENCIAIS_FISCAIS.CSC_PRODUCAO': 'CIFRADO — CSC de produção.',
    'CREDENCIAIS_FISCAIS.FOCUS_TOKEN_HOMOLOGACAO': 'CIFRADO — token Focus NFe de homologação.',
    'CREDENCIAIS_FISCAIS.FOCUS_TOKEN_PRODUCAO': 'CIFRADO — token Focus NFe de produção.',
    'CREDENCIAIS_FISCAIS.FOCUS_TOKEN_PRINCIPAL': 'CIFRADO — token principal da conta Focus (sincronização da empresa).',
    'CREDENCIAIS_FISCAIS.SINCRONIZADO_EM': 'Última sincronização com a Focus.',
    'CREDENCIAIS_FISCAIS.ATUALIZADO_EM': 'Última alteração.',
    'NOTAS_FISCAIS.ID': 'Identificador interno (nf-xxxxxxxxxxxx).',
    'NOTAS_FISCAIS.LOJA_ID': 'Loja emitente.',
    'NOTAS_FISCAIS.ENTREGA_ID': 'Comanda de entrega.',
    'NOTAS_FISCAIS.PEDIDO_ID': 'Venda (pedido de origem) — trava 1 nota ativa por venda.',
    'NOTAS_FISCAIS.MODELO': 'NFCE (65) | NFE (55).',
    'NOTAS_FISCAIS.NUMERO': 'Número da nota.',
    'NOTAS_FISCAIS.SERIE': 'Série.',
    'NOTAS_FISCAIS.CHAVE': 'Chave de acesso (44 dígitos).',
    'NOTAS_FISCAIS.PROTOCOLO': 'Protocolo de autorização da SEFAZ.',
    'NOTAS_FISCAIS.STATUS': 'AUTORIZADA | PROCESSANDO | REJEITADA | CANCELADA | ERRO.',
    'NOTAS_FISCAIS.AMBIENTE': 'HOMOLOGACAO | PRODUCAO.',
    'NOTAS_FISCAIS.PROVEDOR': 'MOCK (simulado) | FOCUSNFE.',
    'NOTAS_FISCAIS.REF_PROVEDOR': 'Referência enviada ao provedor (idempotência).',
    'NOTAS_FISCAIS.VALOR_TOTAL': 'Valor total da nota.',
    'NOTAS_FISCAIS.DANFE_URL': 'PDF oficial do DANFE (Focus).',
    'NOTAS_FISCAIS.XML_URL': 'XML autorizado (Focus).',
    'NOTAS_FISCAIS.QRCODE_URL': 'URL do QR Code da NFC-e.',
    'NOTAS_FISCAIS.URL_CONSULTA': 'Portal de consulta da NFC-e.',
    'NOTAS_FISCAIS.MENSAGEM': 'Retorno da SEFAZ/provedor.',
    'NOTAS_FISCAIS.DADOS': 'Snapshot completo do documento (emitente, destinatário, itens, totais) em JSON.',
    'NOTAS_FISCAIS.EMITIDA_EM': 'Data de autorização.',
    'NOTAS_FISCAIS.CRIADO_EM': 'Criação do registro.',
    'NOTAS_FISCAIS.ATUALIZADO_EM': 'Última atualização.',
  },
};
