-- ============================================================================
-- Distre — estrutura completa do banco (gerado de DISTRE_PROD em 2026-10-10)
-- Gerado por backend/scripts/gerar-doc-banco.cjs — NÃO editar à mão; rode o script de novo.
--
-- Recriar do zero:  sqlcmd -S localhost\SQLEXPRESS -E -i backend\docs\schema-completo.sql
-- (troque o nome do banco abaixo se quiser outro). Contém só ESTRUTURA, sem dados.
-- Observação: o backend também cria/ajusta essas tabelas sozinho ao subir
-- (database.ts e fiscal/fiscalRepo.ts) — este script é a cópia de segurança em texto.
-- ============================================================================
-- Índices filtrados (ex.: CNPJ único das lojas) exigem estas opções; o sqlcmd vem com elas desligadas.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO
IF DB_ID('DISTRE_PROD') IS NULL CREATE DATABASE [DISTRE_PROD];
GO
USE [DISTRE_PROD];
GO

-- Empresas/redes clientes do Distre (multi-tenant). Uma empresa tem várias lojas.
IF OBJECT_ID('EMPRESAS') IS NULL
CREATE TABLE [EMPRESAS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [CNPJ] VARCHAR(20) NOT NULL,
  [TELEFONE] VARCHAR(50) NULL,
  [EMAIL] VARCHAR(100) NULL,
  [ATIVO] BIT NOT NULL CONSTRAINT [DF__EMPRESAS__ATIVO__1BFD2C07] DEFAULT ((1)),
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [STATUS_FINANCEIRO] VARCHAR(50) NOT NULL CONSTRAINT [DF__EMPRESAS__STATUS__286302EC] DEFAULT ('REGULAR'),
  CONSTRAINT [PK__EMPRESAS__3214EC27347F9E29] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ__EMPRESAS__AA57D6B47F3D7F57] UNIQUE ([CNPJ])
);
GO

-- Planos de assinatura do SaaS (Bronze, Silver, Gold, Enterprise) e seus limites.
IF OBJECT_ID('PLANOS') IS NULL
CREATE TABLE [PLANOS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [DESCRICAO] NVARCHAR(MAX) NULL,
  [VALOR_MENSAL] DECIMAL(10, 2) NOT NULL,
  [LIMITE_ENTREGAS_MES] INT NULL,
  [LIMITE_LOJAS] INT NULL,
  [LIMITE_MOTORISTAS] INT NULL,
  [ATIVO] BIT NOT NULL CONSTRAINT [DF__PLANOS__ATIVO__2B3F6F97] DEFAULT ((1)),
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__PLANOS__3214EC275ECE7E8F] PRIMARY KEY ([ID])
);
GO

-- Usuários administradores master do painel (senha com hash bcrypt).
IF OBJECT_ID('ADMINISTRADORES') IS NULL
CREATE TABLE [ADMINISTRADORES] (
  [USUARIO] VARCHAR(100) NOT NULL,
  [SENHA_HASH] VARCHAR(256) NOT NULL,
  CONSTRAINT [PK__ADMINIST__E251F485FE1FC927] PRIMARY KEY ([USUARIO])
);
GO

-- Assinatura de cada empresa/loja a um plano (máquina de estados de cobrança).
IF OBJECT_ID('ASSINATURAS_EMPRESAS') IS NULL
CREATE TABLE [ASSINATURAS_EMPRESAS] (
  [ID] VARCHAR(50) NOT NULL,
  [EMPRESA_ID] VARCHAR(50) NOT NULL,
  [PLANO_ID] VARCHAR(50) NOT NULL,
  [STATUS] VARCHAR(50) NOT NULL CONSTRAINT [DF__ASSINATUR__STATU__300424B4] DEFAULT ('ATIVA'),
  [DIA_VENCIMENTO] INT NOT NULL CONSTRAINT [DF__ASSINATUR__DIA_V__30F848ED] DEFAULT ((10)),
  [VALOR_PERSONALIZADO] DECIMAL(10, 2) NULL,
  [PROXIMO_FATURAMENTO] VARCHAR(100) NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [CANCELADO_EM] VARCHAR(100) NULL,
  [TRIAL_EXPIRA_EM] VARCHAR(100) NULL,
  [GATEWAY_SUBSCRIPTION_ID] VARCHAR(200) NULL,
  [METODO_PAGAMENTO_PADRAO] VARCHAR(20) NULL,
  [SUSPENSA_EM] VARCHAR(100) NULL,
  [LOJA_ID] VARCHAR(50) NULL,
  CONSTRAINT [PK__ASSINATU__3214EC27A5580813] PRIMARY KEY ([ID])
);
GO

-- Dados fiscais do emitente por loja (CNPJ, IE, endereço, provedor, ambiente, séries, tributação padrão).
IF OBJECT_ID('CONFIG_FISCAL_LOJA') IS NULL
CREATE TABLE [CONFIG_FISCAL_LOJA] (
  [LOJA_ID] VARCHAR(50) NOT NULL,
  [RAZAO_SOCIAL] NVARCHAR(200) NOT NULL,
  [NOME_FANTASIA] NVARCHAR(200) NULL,
  [CNPJ] VARCHAR(14) NOT NULL,
  [INSCRICAO_ESTADUAL] VARCHAR(20) NOT NULL,
  [REGIME_TRIBUTARIO] INT NOT NULL,
  [LOGRADOURO] NVARCHAR(200) NOT NULL,
  [NUMERO] NVARCHAR(20) NOT NULL,
  [BAIRRO] NVARCHAR(120) NOT NULL,
  [MUNICIPIO] NVARCHAR(120) NOT NULL,
  [UF] CHAR(2) NOT NULL,
  [CEP] VARCHAR(8) NOT NULL,
  [TELEFONE] VARCHAR(20) NULL,
  [AMBIENTE] VARCHAR(12) NOT NULL,
  [SERIE_NFCE] INT NOT NULL,
  [PROXIMO_NUMERO_NFCE] INT NOT NULL,
  [SERIE_NFE] INT NOT NULL,
  [PROXIMO_NUMERO_NFE] INT NOT NULL,
  [NCM_PADRAO] VARCHAR(8) NOT NULL,
  [CFOP_PADRAO] VARCHAR(4) NOT NULL,
  [ICMS_SITUACAO_PADRAO] VARCHAR(4) NOT NULL,
  [ORIGEM_PADRAO] VARCHAR(1) NOT NULL,
  [TOKEN_PROVEDOR] NVARCHAR(200) NULL,
  [ATUALIZADO_EM] VARCHAR(100) NOT NULL,
  [PROVEDOR] VARCHAR(12) NOT NULL CONSTRAINT [DF_CFL_PROVEDOR] DEFAULT ('SIMULADO'),
  [PERCENTUAL_TRIBUTOS] DECIMAL(5, 2) NOT NULL CONSTRAINT [DF_CFL_TRIBUTOS] DEFAULT ((0)),
  [EMAIL] NVARCHAR(120) NULL,
  CONSTRAINT [PK__CONFIG_F__071BC451F393A3AE] PRIMARY KEY ([LOJA_ID])
);
GO

-- Parâmetros globais da régua de cobrança (dunning): carência, multa, juros, avisos.
IF OBJECT_ID('CONFIGURACOES_COBRANCA') IS NULL
CREATE TABLE [CONFIGURACOES_COBRANCA] (
  [ID] VARCHAR(50) NOT NULL CONSTRAINT [DF__CONFIGURACOE__ID__3A81B327] DEFAULT ('default'),
  [DIAS_CARENCIA_BLOQUEIO] INT NOT NULL CONSTRAINT [DF__CONFIGURA__DIAS___3B75D760] DEFAULT ((5)),
  [MULTA_PERCENTUAL] DECIMAL(5, 2) NOT NULL CONSTRAINT [DF__CONFIGURA__MULTA__3C69FB99] DEFAULT ((2.00)),
  [JUROS_MES_PERCENTUAL] DECIMAL(5, 2) NOT NULL CONSTRAINT [DF__CONFIGURA__JUROS__3D5E1FD2] DEFAULT ((1.00)),
  [EMAIL_NOTIFICACAO_DIAS_ANTES] INT NOT NULL CONSTRAINT [DF__CONFIGURA__EMAIL__3E52440B] DEFAULT ((3)),
  [WHATSAPP_NOTIFICACAO_DIAS_ATRASO] INT NOT NULL CONSTRAINT [DF__CONFIGURA__WHATS__3F466844] DEFAULT ((2)),
  CONSTRAINT [PK__CONFIGUR__3214EC274B91C243] PRIMARY KEY ([ID])
);
GO

-- Segredos fiscais por loja — certificado A1, senha, CSC e tokens da Focus NFe — TODOS CIFRADOS (AES-256-GCM).
IF OBJECT_ID('CREDENCIAIS_FISCAIS') IS NULL
CREATE TABLE [CREDENCIAIS_FISCAIS] (
  [LOJA_ID] VARCHAR(50) NOT NULL,
  [CERT_PFX] NVARCHAR(MAX) NULL,
  [CERT_SENHA] NVARCHAR(400) NULL,
  [CERT_TITULAR] NVARCHAR(200) NULL,
  [CERT_CNPJ] VARCHAR(14) NULL,
  [CERT_VALIDO_ATE] VARCHAR(40) NULL,
  [CSC_ID_HOMOLOGACAO] VARCHAR(10) NULL,
  [CSC_HOMOLOGACAO] NVARCHAR(400) NULL,
  [CSC_ID_PRODUCAO] VARCHAR(10) NULL,
  [CSC_PRODUCAO] NVARCHAR(400) NULL,
  [FOCUS_TOKEN_HOMOLOGACAO] NVARCHAR(400) NULL,
  [FOCUS_TOKEN_PRODUCAO] NVARCHAR(400) NULL,
  [FOCUS_TOKEN_PRINCIPAL] NVARCHAR(400) NULL,
  [SINCRONIZADO_EM] VARCHAR(100) NULL,
  [ATUALIZADO_EM] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__CREDENCI__071BC451A26B0336] PRIMARY KEY ([LOJA_ID])
);
GO

-- Comandas: pedidos (tipo "pedido") e entregas (tipo "entrega") com todo o ciclo de vida, rota, telemetria e comprovante (POD).
IF OBJECT_ID('ENTREGAS') IS NULL
CREATE TABLE [ENTREGAS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME_CLIENTE] NVARCHAR(255) NOT NULL,
  [ENDERECO] NVARCHAR(MAX) NOT NULL,
  [ITENS] NVARCHAR(MAX) NOT NULL,
  [PRIORIDADE] VARCHAR(50) NOT NULL,
  [TIPO_CARGA] VARCHAR(50) NOT NULL,
  [STATUS] VARCHAR(50) NOT NULL,
  [MOTORISTA] NVARCHAR(MAX) NULL,
  [ROTA] NVARCHAR(MAX) NULL,
  [TELEMETRIA] NVARCHAR(MAX) NULL,
  [INCIDENTES] NVARCHAR(MAX) NULL,
  [URL_WEBHOOK] NVARCHAR(MAX) NULL,
  [LOGS_WEBHOOK] NVARCHAR(MAX) NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [ATUALIZADO_EM] VARCHAR(100) NOT NULL,
  [RECEBEDOR_NOME] NVARCHAR(255) NULL,
  [RECEBEDOR_CPF] NVARCHAR(50) NULL,
  [COMPROVANTE_FOTO_URL] NVARCHAR(500) NULL,
  [ASSINATURA_BASE64] NVARCHAR(MAX) NULL,
  [JUSTIFICATIVA_DESVIO_COORDENADA] NVARCHAR(MAX) NULL,
  [DATA_HORA_CONCLUSAO] VARCHAR(100) NULL,
  [SEQUENCIA_ESPERADA] INT NULL,
  [SEQUENCIA_REALIZADA] INT NULL,
  [VALOR] DECIMAL(10, 2) NULL,
  [LOJA_ID] VARCHAR(100) NULL,
  [NOME_LOJA] NVARCHAR(255) NULL,
  [NOME_EMPRESA] NVARCHAR(255) NULL,
  [CLIENTE_DOCUMENTO] NVARCHAR(50) NULL,
  [ROMANEIO_ID] VARCHAR(100) NULL,
  [BAIRRO] NVARCHAR(255) NULL,
  [CIDADE] NVARCHAR(255) NULL,
  [FORMA_PAGAMENTO] VARCHAR(100) NULL,
  [DESPACHADO_EM] VARCHAR(100) NULL,
  [TIPO_COMANDA] VARCHAR(50) NOT NULL CONSTRAINT [DF__ENTREGAS__TIPO_C__108B795B] DEFAULT ('entrega'),
  [REFERENCIA] NVARCHAR(MAX) NULL,
  [DESTINO_LAT] FLOAT NULL,
  [DESTINO_LNG] FLOAT NULL,
  CONSTRAINT [PK__ENTREGAS__3214EC276093B0DC] PRIMARY KEY ([ID])
);
GO

-- Extrato do estoque: toda entrada, venda, estorno e ajuste. A chave de idempotência impede lançar o mesmo evento duas vezes.
IF OBJECT_ID('ESTOQUE_MOVIMENTOS') IS NULL
CREATE TABLE [ESTOQUE_MOVIMENTOS] (
  [ID] BIGINT IDENTITY(1,1) NOT NULL,
  [LOJA_ID] VARCHAR(100) NOT NULL,
  [PRODUTO_ID] VARCHAR(100) NOT NULL,
  [TIPO] VARCHAR(20) NOT NULL,
  [QUANTIDADE] INT NOT NULL,
  [REFERENCIA] NVARCHAR(200) NULL,
  [CHAVE] VARCHAR(120) NOT NULL,
  [CRIADO_EM] DATETIME2 NOT NULL CONSTRAINT [DF__ESTOQUE_M__CRIAD__5441852A] DEFAULT (sysutcdatetime()),
  CONSTRAINT [PK__ESTOQUE___3214EC27F99013FD] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ_ESTOQUE_MOVIMENTO] UNIQUE ([LOJA_ID], [PRODUTO_ID], [TIPO], [CHAVE])
);
GO

-- Saldo físico de cada produto por loja. Só existe linha para produtos com controle de estoque (após o 1º recebimento); sem linha = "Sem controle". SALDO nunca fica negativo (CHECK).
IF OBJECT_ID('ESTOQUE_SALDOS') IS NULL
CREATE TABLE [ESTOQUE_SALDOS] (
  [LOJA_ID] VARCHAR(100) NOT NULL,
  [PRODUTO_ID] VARCHAR(100) NOT NULL,
  [SALDO] INT NOT NULL,
  CONSTRAINT [PK_ESTOQUE_SALDOS] PRIMARY KEY ([LOJA_ID], [PRODUTO_ID])
);
GO

-- Faturas mensais da assinatura (Pix/boleto/cartão via gateway de pagamento).
IF OBJECT_ID('FATURAS') IS NULL
CREATE TABLE [FATURAS] (
  [ID] VARCHAR(50) NOT NULL,
  [EMPRESA_ID] VARCHAR(50) NOT NULL,
  [ASSINATURAS_EMPRESAS_ID] VARCHAR(50) NULL,
  [VALOR_BRUTO] DECIMAL(10, 2) NOT NULL,
  [VALOR_DESCONTO] DECIMAL(10, 2) NOT NULL CONSTRAINT [DF__FATURAS__VALOR_D__34C8D9D1] DEFAULT ((0.00)),
  [STATUS] VARCHAR(50) NOT NULL CONSTRAINT [DF__FATURAS__STATUS__35BCFE0A] DEFAULT ('PENDENTE'),
  [DATA_EMISSAO] VARCHAR(100) NOT NULL,
  [DATA_VENCIMENTO] VARCHAR(100) NOT NULL,
  [DATA_PAGAMENTO] VARCHAR(100) NULL,
  [REFERENCIA_MES_ANO] VARCHAR(20) NOT NULL,
  [GATEWAY_FATURA_ID] VARCHAR(200) NULL,
  [BOLETO_URL] NVARCHAR(500) NULL,
  [PIX_COPIA_COLA] NVARCHAR(500) NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [METODO_PAGAMENTO] VARCHAR(20) NULL,
  [TENTATIVAS_COBRANCA] INT NOT NULL CONSTRAINT [DF__FATURAS__TENTATI__403A8C7D] DEFAULT ((0)),
  [PROXIMA_ACAO_DUNNING] VARCHAR(100) NULL,
  [LOJA_ID] VARCHAR(50) NULL,
  CONSTRAINT [PK__FATURAS__3214EC27A0694E8F] PRIMARY KEY ([ID])
);
GO

-- Transações de pagamento registradas para cada fatura.
IF OBJECT_ID('HISTORICO_PAGAMENTOS') IS NULL
CREATE TABLE [HISTORICO_PAGAMENTOS] (
  [ID] VARCHAR(50) NOT NULL,
  [FATURA_ID] VARCHAR(50) NOT NULL,
  [METODO_PAGAMENTO] VARCHAR(100) NOT NULL,
  [VALOR_PAGO] DECIMAL(10, 2) NOT NULL,
  [DATA_TRANSACAO] VARCHAR(100) NOT NULL,
  [STATUS_TRANSACAO] VARCHAR(50) NOT NULL,
  [GATEWAY_TRANSACAO_ID] VARCHAR(200) NULL,
  [LOG_TRANSACAO] NVARCHAR(MAX) NULL,
  CONSTRAINT [PK__HISTORIC__3214EC27A8508667] PRIMARY KEY ([ID])
);
GO

-- Razão financeiro imutável (append-only, encadeado por hash). Trigger bloqueia UPDATE/DELETE.
IF OBJECT_ID('LEDGER_FINANCEIRO') IS NULL
CREATE TABLE [LEDGER_FINANCEIRO] (
  [SEQ] BIGINT IDENTITY(1,1) NOT NULL,
  [ID] VARCHAR(50) NOT NULL,
  [EMPRESA_ID] VARCHAR(50) NOT NULL,
  [ASSINATURA_ID] VARCHAR(50) NULL,
  [FATURA_ID] VARCHAR(50) NULL,
  [TIPO_LANCAMENTO] VARCHAR(40) NOT NULL,
  [VALOR] DECIMAL(14, 2) NOT NULL,
  [MOEDA] VARCHAR(3) NOT NULL CONSTRAINT [DF__LEDGER_FI__MOEDA__49C3F6B7] DEFAULT ('BRL'),
  [ORIGEM] VARCHAR(40) NOT NULL,
  [REFERENCIA_EXTERNA] VARCHAR(200) NULL,
  [METADADOS] NVARCHAR(MAX) NULL,
  [HASH_ANTERIOR] CHAR(64) NULL,
  [HASH_ATUAL] CHAR(64) NOT NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [CRIADO_POR] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__LEDGER_F__CA1938C05F0B0150] PRIMARY KEY ([SEQ]),
  CONSTRAINT [UQ__LEDGER_F__3214EC26C05C55D7] UNIQUE ([ID])
);
GO

-- Log de todas as mensagens que passam pelo barramento de eventos (broker).
IF OBJECT_ID('LOGS_EVENTOS') IS NULL
CREATE TABLE [LOGS_EVENTOS] (
  [ID] VARCHAR(50) NOT NULL,
  [TOPICO] VARCHAR(150) NOT NULL,
  [ENTREGA_ID] VARCHAR(50) NOT NULL,
  [CONTEUDO] NVARCHAR(MAX) NOT NULL,
  [TIMESTAMP_REGISTRO] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__LOGS_EVE__3214EC27F60C57EF] PRIMARY KEY ([ID])
);
GO

-- Lojas (filiais) de cada empresa. Cada loja tem login próprio no painel e cardápio/vitrine própria.
IF OBJECT_ID('LOJAS') IS NULL
CREATE TABLE [LOJAS] (
  [ID] VARCHAR(50) NOT NULL,
  [EMPRESA_ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [CNPJ] VARCHAR(20) NULL,
  [ENDERECO] NVARCHAR(500) NULL,
  [NUMERO] NVARCHAR(20) NULL,
  [BAIRRO] NVARCHAR(100) NULL,
  [CIDADE] NVARCHAR(100) NULL,
  [UF] VARCHAR(2) NULL,
  [CEP] VARCHAR(10) NULL,
  [USUARIO] VARCHAR(100) NOT NULL,
  [SENHA_HASH] VARCHAR(256) NOT NULL,
  [CHAVE_ACESSO] VARCHAR(100) NOT NULL,
  [ATIVO] BIT NOT NULL CONSTRAINT [DF__LOJAS__ATIVO__21B6055D] DEFAULT ((1)),
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [RECEBE_PEDIDOS] BIT NOT NULL CONSTRAINT [DF__LOJAS__RECEBE_PE__22AA2996] DEFAULT ((0)),
  [LATITUDE] FLOAT NULL,
  [LONGITUDE] FLOAT NULL,
  [LOGO_URL] NVARCHAR(600) NULL,
  [STATUS_FINANCEIRO] VARCHAR(50) NOT NULL CONSTRAINT [DF__LOJAS__STATUS_FI__412EB0B6] DEFAULT ('REGULAR'),
  CONSTRAINT [PK__LOJAS__3214EC27D648C3BC] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ__LOJAS__9886FDF06A0FD72E] UNIQUE ([CHAVE_ACESSO]),
  CONSTRAINT [UQ__LOJAS__E251F484DE1791F4] UNIQUE ([USUARIO])
);
GO

-- Entregadores (motoboys) vinculados a uma loja e ao app do entregador.
IF OBJECT_ID('MOTORISTAS') IS NULL
CREATE TABLE [MOTORISTAS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [TIPO_VEICULO] VARCHAR(50) NOT NULL,
  [STATUS] VARCHAR(50) NOT NULL,
  [LOJA_ID] VARCHAR(100) NULL,
  [CODIGO_VINCULO] VARCHAR(50) NOT NULL,
  [DISPOSITIVO_CONECTADO] BIT NOT NULL CONSTRAINT [DF__MOTORISTA__DISPO__182C9B23] DEFAULT ((0)),
  [X] INT NULL,
  [Y] INT NULL,
  [ULTIMA_ATUALIZACAO] VARCHAR(100) NULL,
  CONSTRAINT [PK__MOTORIST__3214EC27F39CC5E3] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ__MOTORIST__ED462DCF94B16F8F] UNIQUE ([CODIGO_VINCULO])
);
GO

-- NFC-e (modelo 65) e NF-e (modelo 55) emitidas, com chave, protocolo, status e o snapshot completo do documento.
IF OBJECT_ID('NOTAS_FISCAIS') IS NULL
CREATE TABLE [NOTAS_FISCAIS] (
  [ID] VARCHAR(50) NOT NULL,
  [LOJA_ID] VARCHAR(50) NOT NULL,
  [ENTREGA_ID] VARCHAR(50) NULL,
  [PEDIDO_ID] VARCHAR(50) NULL,
  [MODELO] VARCHAR(4) NOT NULL,
  [NUMERO] INT NULL,
  [SERIE] INT NULL,
  [CHAVE] VARCHAR(44) NULL,
  [PROTOCOLO] VARCHAR(30) NULL,
  [STATUS] VARCHAR(12) NOT NULL,
  [AMBIENTE] VARCHAR(12) NOT NULL,
  [PROVEDOR] VARCHAR(20) NOT NULL,
  [REF_PROVEDOR] VARCHAR(60) NOT NULL,
  [VALOR_TOTAL] DECIMAL(12, 2) NOT NULL,
  [DANFE_URL] NVARCHAR(600) NULL,
  [XML_URL] NVARCHAR(600) NULL,
  [QRCODE_URL] NVARCHAR(1000) NULL,
  [URL_CONSULTA] NVARCHAR(600) NULL,
  [MENSAGEM] NVARCHAR(1000) NULL,
  [DADOS] NVARCHAR(MAX) NOT NULL,
  [EMITIDA_EM] VARCHAR(100) NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [ATUALIZADO_EM] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__NOTAS_FI__3214EC270E576E1A] PRIMARY KEY ([ID])
);
GO

-- Produtos que faltaram na separação: o que saiu do pedido (ou o motivo do cancelamento), quantas unidades, por quê e o desfecho. Auditoria da tela "Em falta".
IF OBJECT_ID('PEDIDO_CONFERENCIA_FALTAS') IS NULL
CREATE TABLE [PEDIDO_CONFERENCIA_FALTAS] (
  [ID] BIGINT IDENTITY(1,1) NOT NULL,
  [PEDIDO_ID] VARCHAR(100) NOT NULL,
  [PRODUTO_ID] VARCHAR(100) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [QUANTIDADE] INT NOT NULL,
  [PRECO] DECIMAL(10, 2) NULL,
  [MOTIVO] NVARCHAR(200) NOT NULL,
  [DESFECHO] VARCHAR(20) NOT NULL,
  [CHAVE] VARCHAR(100) NOT NULL,
  [CRIADO_EM] DATETIME2 NOT NULL CONSTRAINT [DF__PEDIDO_CO__CRIAD__60A75C0F] DEFAULT (sysutcdatetime()),
  CONSTRAINT [PK__PEDIDO_C__3214EC2798C986EF] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ_CONFERENCIA_FALTA] UNIQUE ([PEDIDO_ID], [CHAVE])
);
GO

-- Itens de cada pedido a conferir na separação (por produto), com a quantidade pedida e quantas unidades já foram lidas pelo EAN.
IF OBJECT_ID('PEDIDO_CONFERENCIA_ITENS') IS NULL
CREATE TABLE [PEDIDO_CONFERENCIA_ITENS] (
  [PEDIDO_ID] VARCHAR(100) NOT NULL,
  [PRODUTO_ID] VARCHAR(100) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [EAN] VARCHAR(14) NULL,
  [QUANTIDADE] INT NOT NULL,
  [CONFERIDA] INT NOT NULL CONSTRAINT [DF__PEDIDO_CO__CONFE__5812160E] DEFAULT ((0)),
  [PRECO] DECIMAL(10, 2) NULL,
  CONSTRAINT [PK__PEDIDO_C__2BDE52533017CF7C] PRIMARY KEY ([PEDIDO_ID], [PRODUTO_ID])
);
GO

-- Leituras de código de barras da conferência. A chave torna a leitura idempotente: o mesmo envio repetido não conta duas vezes.
IF OBJECT_ID('PEDIDO_CONFERENCIA_LEITURAS') IS NULL
CREATE TABLE [PEDIDO_CONFERENCIA_LEITURAS] (
  [PEDIDO_ID] VARCHAR(100) NOT NULL,
  [CHAVE] VARCHAR(100) NOT NULL,
  [EAN] VARCHAR(14) NOT NULL,
  [CRIADO_EM] DATETIME2 NOT NULL CONSTRAINT [DF__PEDIDO_CO__CRIAD__5BE2A6F2] DEFAULT (sysutcdatetime()),
  CONSTRAINT [PK__PEDIDO_C__A15C5210399AE18C] PRIMARY KEY ([PEDIDO_ID], [CHAVE])
);
GO

-- Produtos do cardápio/vitrine de cada loja, com dados fiscais opcionais por produto.
IF OBJECT_ID('PRODUTOS') IS NULL
CREATE TABLE [PRODUTOS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  [PRECO] DECIMAL(10, 2) NOT NULL,
  [LOJA_ID] VARCHAR(100) NULL,
  [ATIVO] BIT NOT NULL CONSTRAINT [DF__PRODUTOS__ATIVO__276EDEB3] DEFAULT ((1)),
  [IMAGEM_URL] NVARCHAR(500) NULL,
  [DESCRICAO] NVARCHAR(MAX) NULL,
  [CATEGORIA] NVARCHAR(120) NULL,
  [SUBCATEGORIA] NVARCHAR(120) NULL,
  [NCM] VARCHAR(8) NULL,
  [CEST] VARCHAR(7) NULL,
  [CFOP] VARCHAR(4) NULL,
  [ICMS_SITUACAO] VARCHAR(4) NULL,
  [UNIDADE] VARCHAR(6) NULL,
  [CODIGO_BARRAS] VARCHAR(14) NULL,
  CONSTRAINT [PK__PRODUTOS__3214EC272323DC32] PRIMARY KEY ([ID])
);
GO

-- Sessões de login persistidas (sobrevivem a reinício do servidor).
IF OBJECT_ID('SESSOES') IS NULL
CREATE TABLE [SESSOES] (
  [TOKEN] VARCHAR(100) NOT NULL,
  [TIPO] VARCHAR(20) NOT NULL,
  [LOJA_ID] VARCHAR(50) NULL,
  [NOME_LOJA] NVARCHAR(200) NULL,
  [NOME_EMPRESA] NVARCHAR(200) NULL,
  [RECEBE_PEDIDOS] BIT NULL,
  [LATITUDE] FLOAT NULL,
  [LONGITUDE] FLOAT NULL,
  [CRIADO_EM] VARCHAR(100) NOT NULL,
  [EXPIRA_EM] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK__SESSOES__05BE64ECB8ACFCB5] PRIMARY KEY ([TOKEN])
);
GO

-- Catálogo de tipos de veículo da frota.
IF OBJECT_ID('TIPOS_VEICULOS') IS NULL
CREATE TABLE [TIPOS_VEICULOS] (
  [ID] VARCHAR(50) NOT NULL,
  [NOME] NVARCHAR(255) NOT NULL,
  CONSTRAINT [PK__TIPOS_VE__3214EC27AA1EE392] PRIMARY KEY ([ID])
);
GO

-- Webhooks recebidos do gateway de pagamento (ingestão idempotente + fila de reprocessamento).
IF OBJECT_ID('WEBHOOK_EVENTS') IS NULL
CREATE TABLE [WEBHOOK_EVENTS] (
  [ID] VARCHAR(50) NOT NULL,
  [GATEWAY_EVENT_ID] VARCHAR(200) NOT NULL,
  [GATEWAY] VARCHAR(30) NOT NULL,
  [EVENT_TYPE] VARCHAR(80) NOT NULL,
  [PAYLOAD] NVARCHAR(MAX) NOT NULL,
  [ASSINATURA_HMAC] VARCHAR(300) NULL,
  [STATUS] VARCHAR(20) NOT NULL CONSTRAINT [DF__WEBHOOK_E__STATU__44FF419A] DEFAULT ('PENDENTE'),
  [TENTATIVAS] INT NOT NULL CONSTRAINT [DF__WEBHOOK_E__TENTA__45F365D3] DEFAULT ((0)),
  [PROXIMA_TENTATIVA] VARCHAR(100) NULL,
  [ERRO_ULTIMO] NVARCHAR(MAX) NULL,
  [RECEBIDO_EM] VARCHAR(100) NOT NULL,
  [PROCESSADO_EM] VARCHAR(100) NULL,
  CONSTRAINT [PK__WEBHOOK___3214EC27389C9F8F] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ_WEBHOOK_EVENT] UNIQUE ([GATEWAY], [GATEWAY_EVENT_ID])
);
GO

-- Chaves estrangeiras
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('LOJAS') AND referenced_object_id = OBJECT_ID('EMPRESAS'))
  ALTER TABLE [LOJAS] ADD FOREIGN KEY ([EMPRESA_ID]) REFERENCES [EMPRESAS] ([ID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('ASSINATURAS_EMPRESAS') AND referenced_object_id = OBJECT_ID('EMPRESAS'))
  ALTER TABLE [ASSINATURAS_EMPRESAS] ADD FOREIGN KEY ([EMPRESA_ID]) REFERENCES [EMPRESAS] ([ID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('FATURAS') AND referenced_object_id = OBJECT_ID('EMPRESAS'))
  ALTER TABLE [FATURAS] ADD FOREIGN KEY ([EMPRESA_ID]) REFERENCES [EMPRESAS] ([ID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('ASSINATURAS_EMPRESAS') AND referenced_object_id = OBJECT_ID('PLANOS'))
  ALTER TABLE [ASSINATURAS_EMPRESAS] ADD FOREIGN KEY ([PLANO_ID]) REFERENCES [PLANOS] ([ID]);
GO

-- Índices
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UIX_LOJAS_CNPJ')
  CREATE UNIQUE INDEX [UIX_LOJAS_CNPJ] ON [LOJAS] ([CNPJ]) WHERE ([CNPJ] IS NOT NULL);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_WEBHOOK_STATUS')
  CREATE INDEX [IX_WEBHOOK_STATUS] ON [WEBHOOK_EVENTS] ([STATUS], [PROXIMA_TENTATIVA]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_NOTAS_FISCAIS_LOJA')
  CREATE INDEX [IX_NOTAS_FISCAIS_LOJA] ON [NOTAS_FISCAIS] ([LOJA_ID], [CRIADO_EM]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_NOTAS_FISCAIS_PEDIDO')
  CREATE INDEX [IX_NOTAS_FISCAIS_PEDIDO] ON [NOTAS_FISCAIS] ([PEDIDO_ID]);
GO

-- Triggers
IF OBJECT_ID('TRG_LEDGER_IMUTAVEL', 'TR') IS NOT NULL DROP TRIGGER [TRG_LEDGER_IMUTAVEL];
GO
CREATE TRIGGER TRG_LEDGER_IMUTAVEL ON LEDGER_FINANCEIRO
            INSTEAD OF UPDATE, DELETE AS
            BEGIN
              RAISERROR('LEDGER_FINANCEIRO e append-only: UPDATE/DELETE proibido.', 16, 1);
              ROLLBACK TRANSACTION;
            END
GO
